### ISSUE TITLE
Missing API declaration - 01.05.24

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#1005]
ITMS-91053: Missing API declaration - Your app’s code in the “Kodi Remote” file references one or more APIs that require reasons, including the following API categories: **NSPrivacyAccessedAPICategoryFileTimestamp**. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app’s privacy manifest to provide approved reasons for these APIs used by your app’s code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api.

And same about **NSPrivacyAccessedAPICategoryUserDefaults**

**Comment by wutschel** [comment]
If I read it correct I need to add

```
"NSPrivacyAccessedAPIType": "NSPrivacyAccessedAPICategoryUserDefaults"
"NSPrivacyAccessedAPIType": "NSPrivacyAccessedAPICategoryFileTimestamp"
"NSPrivacyAccessedAPITypeReasons": [CA92.1, C617.1]
```
(CA92.1  as we read user default for the app's settings only.)
(C617.1 as the image cache removes cached files after 1 month.)

Where does this need to be added?

**Comment by wutschel** [comment]
Like this?

<a href="https://ibb.co/SyQnsqv"><img src="https://i.ibb.co/wgJW0D6/Bildschirmfoto-2024-03-14-um-22-12-28.png" alt="Bildschirmfoto-2024-03-14-um-22-12-28" border="0"></a>

C617.1 because the image cache deletes aged files from image cache.
CA92.1 as we access the app's settings.

**Comment by kambala-decapitator** [comment]
no idea, haven't dived into this topic yet. Can upload a test build from branch to see if the warning would be gone.

**Comment by wutschel** [comment]
Added https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/1008 to handle this. You can give it a try.
