### ISSUE TITLE
iOS17 scroll indicators missing

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#1007]
When building with Xcode 15 or Xcode 14.3.1 the scroll indicator for `UITableView` is visible on iOS 15 simulator, but not on iOS 17. The indicator is enabled in xib, and also enabling explicitly via `[dataList setShowsVerticalScrollIndicator:YES]` shows no effect. The indicator inset (same as the `UITableVIew` inset) and style is correct.

Was there any API change? I am not finding hints on stackoverflow.

**Comment by wutschel** [comment]
For 'UICollectionView' this still works.

**Comment by wutschel** [comment]
@kambala-decapitator, can you look into this and guide me?

**Comment by kambala-decapitator** [comment]
also not aware of any changes in this area. Same behavior on device? Can test on the following devices:
- iOS: 12, 17
- iPadOS: 15, 17

**Comment by wutschel** [comment]
At least it is same on my iPhone with iOS 17.3.1. I have no access to devices with older iOS versions.

**Comment by wutschel** [comment]
Issue is gone when I comment `dataList.tableHeaderView = self.searchController.searchBar;` I am not clear on side effects yet.

**Comment by wutschel** [comment]
Side effects are visible in the library list views where now the list start is hidden behind the search bar.

A workaround is:
```
UIView *myView = [[UIView alloc] initWithFrame:self.searchController.searchBar.frame];
dataList.tableHeaderView = myView;
```

This keeps the layout correct and also the indicators are back. Looks like iOS17 has a problem with `tableHeaderView` being a search bar.
