### ISSUE TITLE
Potential rework of searchbar handling

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#1042]
### Background:
The current implementation is not optimal and shows some unpredictable behaviour. Some of the current seen issues are caused by iOS17 (missing scroll indicator when adding a searchbar as `UITableView`'s `tableHeaderView`, or too wide searchbars). 
But there are general flaws in the implementation like re-creating the searchbar with each switch between list view and collection view, removing and adding searchbar from views multiple times. I prepared a change which reworks this but has a few workarounds which I would like to have 2nd opinion on.

### Premises / Constraints:
- Keep searchbar on top of lists, so pulldown-to-search
- Keep active searchbar detached from list to be able to scroll the filtered result list
- Keep searchbar inside the current library view to support iPad (searchbar sitting inside at the top of the stacked views)
- Keep colored searchbar for album and season views
- Active and inactive searchbar should look same (wherever possible)
- `UITableView`'s `tableHeaderView` must be a `UISearchBar` to handle insets gently

### Changes:
- Only create `self.searchController` once in `viewDidLoad`
- `self.searchController` is the `UISearchController` which is used for an active search and always displayed detached (floating on top of list)
- To activate a search dedicated  a`UISearchController` + transparent overlayed `UIView` is created for both list view and collection view. The overlay has a `UITapGestureRecognizer ` which triggers a method to show and activate the central `self.searchController`. This allows keep the same look of the searchbar.
- Only create the inactive searchbar + overlay once for list view and once for collection view in `viewDidLoad`
- Some refactoring to be able to unify the look of the inactive searchbar (the one with the overlay) and the active `self.searchController`

### Code:
https://github.com/wutschel/Official-Kodi-Remote-iOS/tree/rework_searchbar

**Comment by wutschel** [comment]
@kambala-decapitator, would like to hear your opinion on this.

**Comment by kambala-decapitator** [comment]
the proposed changes sound good. Also don't see any issues in the branch from a quick glance.

FYI I've just tested table + search in header and don't see any issues with disappearing scrollbars on 17 simulator:

```swift
    override func viewDidLoad() {
        super.viewDidLoad()

        let tv = UITableView(frame: view.bounds, style: .plain)
        tv.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        tv.dataSource = self
        tv.register(UITableViewCell.self, forCellReuseIdentifier: "cell")
        tv.tableHeaderView = UISearchBar(frame: .init(origin: .zero, size: .init(width: view.bounds.width, height: 40)))
        view.addSubview(tv)
    }
```

**Comment by wutschel** [comment]
> the proposed changes sound good. Also don't see any issues in the branch from a quick glance.

Thanks, will raise a PR then. 

> FYI I've just tested table + search in header and don't see any issues with disappearing scrollbars on 17 simulator:

Fascinating. On the App's master the scroll indicators are not shown. They come back as soon you simply comment one code line:
```
// Ensure the searchController is properly attached to the dataList header view.
//dataList.tableHeaderView = self.searchController.searchBar;
```
Does using objective C make a difference? I will also try to not use xib and add the `UITableView` programmatically like you did in your example.

**Comment by kambala-decapitator** [comment]
> Does using objective C make a difference?

of course not :)

> I will also try to not use xib and add the UITableView programmatically like you did in your example.

good idea, this _might_ make a difference

> They come back as soon you simply comment one code line:

is that a single setting of the searchbar? or it's done multiple times?

**Comment by wutschel** [comment]
> good idea, this _might_ make a difference

It had no impact ... 
```
dataList = [[UITableView alloc] initWithFrame:self.view.bounds];
dataList.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
dataList.delegate = self;
dataList.dataSource = self;
dataList.tableHeaderView = [UISearchController new].searchBar;
//option2 dataList.tableHeaderView = [[UISearchBar new];
//option3 dataList.tableHeaderView = [[UISearchBar alloc] initWithFrame:CGRectMake(0, 0, self.view.bounds.size.width, 40)];
[self.view addSubview:dataList];
```
The only option of the above which actually shows the scroll indicator is option 2. But this does not show a search bar.

> is that a single setting of the searchbar? or it's done multiple times?

There is another place as well, but that other occurrence is only used when opening/closing TV show seasons.

**Comment by kambala-decapitator** [comment]
Then it must be some customization further in the code.

This looks weird, don't use such pattern: `[UISearchController new].searchBar`

**Comment by wutschel** [comment]
> Then it must be some customization further in the code.

I commented the code setting anything related to `dataList`. I fear it has to do with the view hierarchy which is a bit weird to me as well. Some ancient code/views in there which git introduced for iPad ...

> This looks weird, don't use such pattern: `[UISearchController new].searchBar`

Sure, did this only to test around the effect.

Btw, another weird effect. When I create `UISearchController` I can set the `tintColor` for the `searchBar` inside it. When I only create a `UISearchBar` this does not work. I am puzzled.

**Comment by kambala-decapitator** [comment]
> I fear it has to do with the view hierarchy which is a bit weird to me as well. Some ancient code/views is in there which got introduced for iPad ...

Also possible, but need to see what's going on in there

**Comment by wutschel** [comment]
Ok, did another change to remove this iPad related additional UIView layer (see https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/1043). I don't think this is needed anymore since a while and tests looked good sa far. But still no scroll indicator.

**Comment by wutschel** [comment]
> Also possible, but need to see what's going on in there

Having a look from your side would be great. 
- The issue happens on both iPad and iPhone. 
- It started with iOS 17 
- It seems independent of the Xcode version (builds from both 14.3.1 and 15.2 show it).
- It happens in other controllers as well, just tested in RightMenuViewController

**Comment by wutschel** [comment]
Let's close. The rework has been merged and the issue around scroll indicators is handled in another issue.
