### ISSUE TITLE
Use dictionaries instead of arrays in AppDelegate

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#1102]
Several menu structure elements like `mainMethod`, `mainParamaters` and others are created as `NSArray` and are then changed to `NSDictionary` by using `indexKeyedDictionaryFromArray`. It is desired to use `NSDictionary` right from the start.

**Comment by wutschel** [comment]
@kambala-decapitator, avoided this rework for a long time (as last time I ended up in crashes I couldn't explain). This time I did this is many baby steps and finally could finish the migration. A hell lot of work, but the code readability improved and the conversion methods from array to dictionary are finally history.

**Comment by kambala-decapitator** [comment]
glad to hear that! Pretty sure it was a PITA to do that... :)

**Comment by wutschel** [comment]
indeed :)
