### ISSUE TITLE
Screen not fully used on some larger iPhone devices (e.g. iPhone 12 Pro Max)

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#111]
Issue was reported in https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/99#issuecomment-757375201:

> on the iPhone 12Pro also the remote control is not scaled to the screen

and in https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/99#issuecomment-757130982:

> TV Shows layout is broken since one of the recent commits. Banners don't expand to the whole width, at least not on my 12 Pro.

Background is given in https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/99#issuecomment-757376880:

>  In the code there are some places where a transform-factor is defined for iPhone X, 6 and 6+. I came across this earlier when updating the NowPlaying screen. This needs some rework.

**Comment by heitbaum** [comment]
@wutschel - we have just submitted feedback from both iPhone12Pro and iPad. Scaling definitely better. Also shared the old layout that was on the iPhone 12Pro. Excellent work. I’ll put these comments in the PR too.
