### ISSUE TITLE
bad layout of TV Shows cells

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#116]
XR iOS 14:
![Screen Shot 2021-01-10 at 18 45 18](https://user-images.githubusercontent.com/1557784/104129692-45628000-537e-11eb-8248-35a77d983c4a.png)

6+ iOS 12:
![Screen Shot 2021-01-10 at 19 21 42](https://user-images.githubusercontent.com/1557784/104129697-51e6d880-537e-11eb-840c-ea9723521bc2.png)

**Comment by kambala-decapitator** [comment]
@wutschel will it be fixed by #112 perhaps?

**Comment by wutschel** [comment]
Could be fixed, yes. Can you check?

**Comment by kambala-decapitator** [comment]
duplicate of #111
