### ISSUE TITLE
Added and corrected german translations

### ISSUE THREAD

**Issue by BBJake** [xbmc/Official-Kodi-Remote-iOS#120]
Hi,

nearly four years ago I created the german translations for Kodi Remote.
Recently i've seen, that new work is done on this project so I reworked my translations and done a PR for this:
https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/119

Hopefully you can merge this in the master branch!

**Comment by kambala-decapitator** [comment]
thanks!

P.S. There was no need to open a separate issue since you already have PR :)
