### ISSUE TITLE
New Kodi Server Dialog on iPad Pro does not work

### ISSUE THREAD

**Issue by heitbaum** [xbmc/Official-Kodi-Remote-iOS#138]
https://pasteboard.co/JKmnYuc.png
In the image above the keyboard lines up below the dialog - but as you can see it pushes the help text over the save button - which stops working. If you minimize the keyboard away, or rotate to portrait it works.
The image below is from when the keyboard is not displayed.
https://pasteboard.co/JKmqeMh.png

This would be a low priority bug.

Device is: A1674 / NLQ62B/A / iPad Pro (9.7-inch) / IOS14.3

**Comment by wutschel** [comment]
Nasty one. Not sure if I can find a good and quick solution. I am even thinking of not allowing to enter the menu while in landscape mode. But this would be hard to figure out from an end-user point of view.

**Comment by heitbaum** [comment]
I’ll take a look when I get back home next week and get in front of the Mac.

**Comment by wutschel** [comment]
I think I found an acceptable workaround. The "tip" text can be hidden when editing starts and we are on an iPad in Landscape mode. The text can be unhidden in all other cases. This allows to let the keyboard come up and still be able to press the "Find Kodi" and "Save" buttons. Could be ok as long as no better solution is found.

Landscape: https://abload.de/img/simulatorscreenshot-i4dk5y.png
Portrait: https://abload.de/img/simulatorscreenshot-ic6k62.png
(Pictures taken from iPad 5th Generation simulator on iOS 14.3)

**Comment by heitbaum** [comment]
Works great and looks fine
