### ISSUE TITLE
First audio track is hidden behind topbar of the playlist

### ISSUE THREAD

**Issue by howie-f** [xbmc/Official-Kodi-Remote-iOS#159]
on a smaller device, iphone5.
after switching from the "Now playing" screen with album cover to the playlist.

eventually already fixed in https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/157

New Rel. 1.6

![IMG_3807](https://user-images.githubusercontent.com/58829855/107148824-a8cbd780-6955-11eb-9f14-088e40386fdb.PNG)

**Comment by wutschel** [comment]
I confirm the big on iPhones with iOS 10.3.1. I am sure this is related to the iOS version as the inset works properly on low resolution iPhones with iOS 14.3. This can be fixed with adding a condition which checks the iOS version (not provided in a PR yet).

**Comment by wutschel** [comment]
Pushed the fix to #157.
