### ISSUE TITLE
1.6 crash reports

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#161]
[AppStore.tar.gz](https://github.com/xbmc/Official-Kodi-Remote-iOS/files/5951442/AppStore.tar.gz)

@wutschel you might want to check.

**Comment by wutschel** [comment]
I looked into this but cannot really see how to make the relevant code more robust.

**Comment by kambala-decapitator** [comment]
these are the top ones:
![Screenshot 2021-02-15 at 15 12 59](https://user-images.githubusercontent.com/1557784/107945284-7139dc80-6fa0-11eb-9c13-0670df22336b.png)

**Comment by kambala-decapitator** [comment]
@wutschel second and third crashes from SS above occur due to some broken logic related to filtering.

I've managed to reproduce the third one: Filter items, clean filter, long press an item -> crash.

You'll also notice that cross and cancel buttons near the searchbar are unresponsive.

**Comment by wutschel** [comment]
Ahh, very good. I can also reproduce this now. I will take a look at this tonight. Thanks!

**Comment by wutschel** [comment]
That was an interesting one. When fixing it I saw at least two other places where this could happen. Underlying issue was that in few places a empty item list was accessed, because the condition did only check for active search, but not for non-empty results.

**Comment by kambala-decapitator** [comment]
dunno if has any relation to crashes, but long press doesn't seem to work on iPad at all

**Comment by wutschel** [comment]
Just tried on the simulator (longpress on album list item), this works. Which use case do you refer to?

**Comment by kambala-decapitator** [comment]
created #170 for that

**Comment by wutschel** [comment]
One of the other crashes (`cellForRowAtIndexPath` in `NowPlaying.m`) could be caused by out-of-bounds access during `[playlistData objectAtIndex:indexPath.row]`. Obviously a variety `objectAtIndex` calls are done without checking the array size before.

But I have no idea where the `pushViewController` crash is coming from. You have got any hint on this?

**Comment by kambala-decapitator** [comment]
> ...could be caused by...

why "could be"? That's exactly the reason based on the stack trace.

> But I have no idea where the pushViewController crash is coming from. You have got any hint on this?

me neither, unfortunately. It's iPhone-only crash though.

**Comment by kambala-decapitator** [comment]
yes, I reproduced it! 
[crashlog.crash.txt](https://github.com/xbmc/Official-Kodi-Remote-iOS/files/5996040/crashlog.crash.txt)

> Opened a tab, changed Auth credentials in Kodi, tried to interact with items a couple of times

**Comment by wutschel** [comment]
Got it. :)

**Comment by wutschel** [comment]
Only 1 crash from the list is left: `[DetailViewController updateChannelListTableCell]`

From the code I am not sure what to do with this.

**Comment by kambala-decapitator** [comment]
I've already tried to fix that in f83b28e9c8fc8fff93988fe1b4c70e9b425a9d9f, but seems I failed

**Comment by wutschel** [comment]
I can reproduce the crash in `[DetailViewController updateChannelListTableCell]` now, stumbled across this while testing something else. Steps:

1. Have an empty radio station list in your PVR channel list
2. Enter "All channel" in the radio menu (2nd bottom item in the TV/PVR main menu)
3. This brings up a JSON error popup (https://abload.de/img/simulatorscreenshot-i5sk22.png).
4. Wait for a few seconds until the crash occurs.

**Comment by wutschel** [comment]
With this code I do not see the crashes anymore. Does this makes sense?

```
-(void)updateChannelListTableCell {
    NSArray* indexPaths = [dataList indexPathsForVisibleRows];
    if ([indexPaths count]>0) {
        [dataList beginUpdates];
        [dataList reloadRowsAtIndexPaths:indexPaths withRowAnimation:UITableViewRowAnimationNone];
        [dataList endUpdates];
    }

    indexPaths = [collectionView indexPathsForVisibleItems];
    if ([indexPaths count]>0) {
        [collectionView reloadItemsAtIndexPaths:indexPaths];
    }
}
```

**Comment by wutschel** [comment]
Btw, did you receive more crash reports which are of interest?

**Comment by kambala-decapitator** [comment]
> With this code I do not see the crashes anymore. Does this makes sense?

not quite sure tbh, but if it prevents the crash, then ok.

> Btw, did you receive more crash reports which are of interest?

yes, there're a few. One of interest is some race condition in EPG. I'll open new issue for 1.6.1 crashes.
