### ISSUE TITLE
long press on iPad doesn't work after searching

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#170]

**Comment by wutschel** [comment]
Just played around with the search on iPad simulator. For me the longpress does not work when I apply it on a filtered list while the search is active. After I pressed Cancel (right side of the search bar) longpress on list items works again. Is this what you are seeing as well?

**Comment by wutschel** [comment]
The code is active, the action sheet is built up, even the origin (`selectedPoint`) is ok. The action sheet is just not visibly presented (`DetailViewController.m`, end of `handleLongPress`). Btw, same bug still exists with the UIAlertView PR.

```
if ([[UIDevice currentDevice] userInterfaceIdiom] == UIUserInterfaceIdiomPhone){
    [action showInView:self.view];
}
 else{
    [action showFromRect:CGRectMake(selectedPoint.x, selectedPoint.y, 1, 1) inView:self.view animated:YES];
}
```

Any idea where to look at?

**Comment by wutschel** [comment]
@kambala-decapitator, I am not sure if I should make above change. With the change the action menu is visible, but I am not sure if this the correct solution for the problem. Your comment is very appreciated.
