### ISSUE TITLE
issues displaying posters and thumbs (14.4 / 2051)

### ISSUE THREAD

**Issue by howie-f** [xbmc/Official-Kodi-Remote-iOS#171]
iPadOS 14.4 - Remote Version 2051
![549255EA-2ED8-477F-91FA-7C517107B419](https://user-images.githubusercontent.com/58829855/108130652-4c348f00-70b0-11eb-85c8-129245e65ead.png)
![6A63456A-208A-48E7-B389-B7CB4459C061](https://user-images.githubusercontent.com/58829855/108130663-4f2f7f80-70b0-11eb-810a-c5d6d7467e85.png)

on iOS 10.3.4 - Remote Version 2029
it looks fine

**Comment by wutschel** [comment]
Too many features and switches ... I never used this switch so far. 
Does this happen with 1.6 from the App Store as well? I hope this is not a regression from the NowPlaying cleanup.

**Comment by wutschel** [comment]
Confirmed. This is related to the rework I did which removed all the magic numbers. But this is a topic which can be resolved, without too many magic numbers and calculations instead. So, I would like to avoid a rollback and implement this scaling and positioning freshly.

I already reached the state shown below. Missing is mainly to take into account the jewel case frame on top/left/bottom/right, and based on this to adapt the size and position of the thumb image. For this I will need to add a few #defines for each jewel case type and calculate the thumb view frame from this. Not too many magic numbers required.

<a href="https://abload.de/image.php?img=simulatorscreenshot-ia1k5w.png"><img src="https://abload.de/img/simulatorscreenshot-ia1k5w.png" /></a>

**Comment by wutschel** [comment]
Not much fun. There are so many special conditions everywhere, and hardcoded offsets, sizes and such...

Do we really need to keep this feature? ;)

**Comment by howie-f** [comment]
> Not much fun.

agreed. dumb this wasn‘t observed earlier. but no pressure, it‘s ready when it‘s ready, i have  some similar hassle in core that was discovered 24hrs ago 😉

**Comment by wutschel** [comment]
@howie-f, what is the desired behavior if the original picture´s aspect ratio is not the targeted one? Currently there are two ways: stretching and masking.

Stretching? First screenshot.
Showing a part of the picture? Second screenshot.

@kambala-decapitator, the missing x-axis offset on the 2nd picture is one of the last issue before I will share a PR. For this one we really need to provide a testflight build. We either need to have more testers with build capability or more testers via testflight. There are too many options and corner cases ...

<a href="https://abload.de/image.php?img=simulatorscreenshot-iulk9b.png"><img src="https://abload.de/img/simulatorscreenshot-iulk9b.png" /></a>

<a href="https://abload.de/image.php?img=simulatorscreenshot-ih6j25.png"><img src="https://abload.de/img/simulatorscreenshot-ih6j25.png" /></a>

**Comment by howie-f** [comment]
i think stretching is better in that case. it‘s my opinion
in your example there seems to be no poster available for that movie, so i‘d say „stretch the thumb“ as the fallback

**Comment by kambala-decapitator** [comment]
> @kambala-decapitator, the missing x-axis offset on the 2nd picture is one of the last issue before I will share a PR. For this one we really need to provide a testflight build. We either need to have more testers with build capability or more testers via testflight. There are too many options and corner cases ...

TF is definitely easier. But we can't force testers to test new feature or even gather more testers just because we want to :)

I'd make 1.6.1 release with bug fixes and afterwards create new TF version with this feature.

**Comment by wutschel** [comment]
> i think stretching is better in that case. it‘s my opinion
> in your example there seems to be no poster available for that movie, so i‘d say „stretch the thumb“ as the fallback

Same opinion here. Looks a bit awkward, but the art isn´t complete in such case anyhow.

**Comment by kambala-decapitator** [comment]
> I would tend to delay for a few days.

fully agree then

**Comment by wutschel** [comment]
Did a bit of bigger rework now, and it still has a few (!) magic numbers. But overall there is lot less hard coding now, and same logic used for NowPlaying and ShowInfoVC. This needs some testing though.

**Comment by howie-f** [comment]
awesome, will check as soon as it arrives tf

**Comment by howie-f** [comment]
noticed a bit fallout, with v 1.6.1 (2063) overlays are misplaced (video and music)


![A9332375-9AB9-4AC7-B0FC-E452A8ECF7FB](https://user-images.githubusercontent.com/58829855/108589978-795b9880-7361-11eb-89d0-77fe21cd7d0a.png)
![49B29B86-7EA5-4DF7-B709-B381A661F70F](https://user-images.githubusercontent.com/58829855/108589984-7e204c80-7361-11eb-9ffe-a6873c6c39f8.png)

**Comment by wutschel** [comment]
As I said, too many features. ;)

Let me see what needs to be done.

**Comment by kambala-decapitator** [comment]
should I reject version waiting for review and wait for the fix?

**Comment by howie-f** [comment]
> should I reject version waiting for review and wait for the fix?

i would suggest this, yes, as it is ux relevant

**Comment by wutschel** [comment]
I agree. Fix is already under test. Not a big deal, I just did not check this feature. :/

**Comment by howie-f** [comment]
> I just did not check this feature. :/

like me 😳

**Comment by wutschel** [comment]
Please check the PR and share your thoughts on the frame dimensions of the details view. I took the option to use the full jewel view size (full NowPlaying screen width). I could also take the thumbview´s dimensions. This will result in a detail view which is shown exactly above the thumb image itself. In case of "Show jewel case" this will feel/look like the backside of the DVD case. But it has reduced space ...
