### ISSUE TITLE
[feature req] pvr overview rework - not an issue

### ISSUE THREAD

**Issue by howie-f** [xbmc/Official-Kodi-Remote-iOS#176]
in my naivety i'm saying that is not a big deal ;) though only a feature request.
can the pvr overview get a bit tuned, like it is faked here for recording no. 2 ? cheers

![Unbenannt](https://user-images.githubusercontent.com/58829855/108420083-9b56fd00-7233-11eb-925f-cc04cbd1bb6f.png)

**Comment by wutschel** [comment]
That will be quite easy to implement as `"art"` is already requested (and provided by Kodi) for recordings. Just need to ensure this is not impacting other thumbviews, and check if this works for timers as well. Looks like this after a 3-lines-of-code change:

<a href="https://abload.de/image.php?img=simulatorscreenshot-ibvjty.png"><img src="https://abload.de/img/simulatorscreenshot-ibvjty.png" /></a>

**Comment by wutschel** [comment]
Implemented and added to #158.

**Comment by howie-f** [comment]
thanks much for implementing this.
can we adjust it so the station logos for pvr recordings (left side) match in size for e.g. channel overview?

![IMG_0113](https://user-images.githubusercontent.com/58829855/111876996-8049eb00-89a1-11eb-837e-4c5c40680ae9.PNG)

**Comment by wutschel** [comment]
Let me look into this.

**Comment by wutschel** [comment]
It´s quite hard to adapt the recording thumb sizes to the current channel list thumb sizes properly. What is easy to achieve is to adapt both thumbs to a similar look. The logos are using the complete cell but with a frame for better readability.

https://abload.de/img/simulatorscreenshot-iq7jti.png
https://abload.de/img/simulatorscreenshot-i3dkes.png
https://abload.de/img/simulatorscreenshot-iz5jdq.png

**Comment by howie-f** [comment]
> It´s quite hard to adapt the recording thumb sizes to the current channel list thumb sizes properly.

sorry, didnt expect this 😏

**Comment by wutschel** [comment]
I find the solution from the PR visually also quite nice. But the PR is raised as draft, maybe I find a better solution. Problem is that the menu level (and logic) in the recordings view is different to the one in the channel list. With the straight forward solution of adding same sizes of the UIImageView I get side effects I do not understand yet. But of course there´s no need to hurry...

**Comment by wutschel** [comment]
Now I think I found a way. But I will ask kambala for some help on this. There is something I do not understand fully yet: To achieve this I need to stop using `dequeueReusableCellWithIdentifier` which I understood makes a performance impact.
