### ISSUE TITLE
shake gesture doesn't work

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#223]
`motionBegan` in app delegate is never called

**Comment by wutschel** [comment]
Yes. Seems to be be broken since ages and before I started to work on the App (I went back to 23c327ea). Not sure yet what to do to fix this.

**Comment by kambala-decapitator** [comment]
basically the fix is to ensure that object responding to motion is first responder, but it doesn't work with app delegate. Also condition is wrong in `motionBegan` implementation.

I can fix that.

**Comment by wutschel** [comment]
This here works for me: https://github.com/wutschel/Official-Kodi-Remote-iOS/tree/fix_shake
Need to remove the `motionBegan` from `AppDelegate.m` though.

**Comment by kambala-decapitator** [comment]
cool. Works on both iPhone and iPad?

**Comment by wutschel** [comment]
Applied your suggestion. And: Yes, works for both iPad and iPhone. I will raise a PR.
