### ISSUE TITLE
TF feedback: “Repeat” and “Shuffle” on iPad don't work

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#224]
The App is awesome as always, however, since updating to 1.6.1 and 1.6.2, the “Repeat” and “Shuffle” button on the Now Playing screen are not working. The same issue does NOT occur on iPhone version, looks like it’s only not functioning on iPad version.

App Version 1.6.2 (2082)

@wutschel

**Comment by wutschel** [comment]
This was already fixed with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/186, merged since 1.6.2 build 2109.
