### ISSUE TITLE
TF feedback: sort issue

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#225]
Sort in asc order by year, sorted by name. Sorting in desc order by year works.

<img src="https://user-images.githubusercontent.com/1557784/113510570-35fd6800-9564-11eb-8313-a32c1369c4ac.jpg" width="50%">

App Version 1.6.2 (2124)

@wutschel

**Comment by wutschel** [comment]
Problem should be solved with https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/198, build in since 1.6.2 build 2142.
