### ISSUE TITLE
AppStore feedback: subtitle and audio buttons don't work

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#226]
Latest update broke the subtitle and audio buttons. When you click them, all you get is "Unavailable." Unacceptable.

@wutschel

**Comment by wutschel** [comment]
Which version is this reported for?

**Comment by wutschel** [comment]
I just tested this on master with a test file from https://github.com/Matroska-Org/matroska-test-files. This works.

**Comment by kambala-decapitator** [comment]
> Which version is this reported for?

current appstore version - 1.6.1

**Comment by wutschel** [comment]
Also 1.6.1 works for me, tested with Kodi 20.0-ALPHA1.

**Comment by kambala-decapitator** [comment]
responded to the user, hopefully we get more info

**Comment by wutschel** [comment]
no feedback? I will ask in the forum, if someone else can double check this.

**Comment by kambala-decapitator** [comment]
> no feedback? I will ask in the forum, if someone else can double check this.

unfortunately, no

**Comment by wutschel** [comment]
Feedback from forum is: no problem with build 2239.

**Comment by wutschel** [comment]
If there is no new information given, we should imo close this. There are no other reports describing this issue and we have positive feedback by the beta-testers from the forum.
