### ISSUE TITLE
Sometimes wrong origin shown when long-pressing on filtered list

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#249]
When long-pressing on filtered list items sometimes a wrong origin is shown. The action carried out is working as expected though.

<a href="https://abload.de/image.php?img=bildschirmfoto2021-04vyj36.png"><img src="https://abload.de/thumb/bildschirmfoto2021-04vyj36.png" /></a>

**Comment by wutschel** [comment]
This is caused by commit 1220d958 in DetailViewController.m which simply changed the cancel action style of the popup from `UIAlertActionStyleDefault` to `UIAlertActionStyleCancel` (which is correct). Also, in case of the situation shown in the screenshot you now hide the keyboard, the origin is moving up to the correct place. Is this possibly a bug in iOS?

**Comment by wutschel** [comment]
I am quite sure this a iOS bug. This occurs when a popup is shown and the bottom is near the keyboard and there is not enough space to shift the popup up. And as mentioned before the origin is fixing itself when hiding the keyboard.

**Comment by wutschel** [comment]
Still same with XCode 13 and iOS 15.

**Comment by wutschel** [comment]
Still same with XCode 14.2.

**Comment by wutschel** [comment]
Still same with XCode 14.3.1

**Comment by wutschel** [comment]
Still happening with Xcode 15.3, but with less offset.

**Comment by wutschel** [comment]
Nothing we can do about it.

**Comment by kambala-decapitator** [comment]
please don't close such as "completed"

**Comment by wutschel** [comment]
> please don't close such as "completed"

Thanks for pointing me to this. Will take care when closing issues in future.
