### ISSUE TITLE
Adjusting volume with volume buttons

### ISSUE THREAD

**Issue by LinusT** [xbmc/Official-Kodi-Remote-iOS#25]
A suggested user experience enhancement.
When application is in foreground let the user change the XBMC volume with the iPhone/iPad/iPod volume buttons in addition to the sliders in the app,

Rationale: it's intuitive and convenient. 

One of the more time critical actions performed in the app is to change volume (to catch the dialog that suddenly went into whisper mode... or to quickly turn down the thumbing bass before the baby wakes up)

**Comment by wutschel** [comment]
@kambala-decapitator, I propose to close this one as we are discussing this in a newer issue (#441).
