### ISSUE TITLE
Appstore feedback: Only display first track of the Album

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#262]
Music Folder Mode

**Comment by wutschel** [comment]
This is truly a bit vague. I now checked entering my music albums (I have flac and musepack encoded albums) in folder mode (via music menu, then folder view, then browsing the folders). I can see all tracks -- as expected.

**Comment by howie-f** [comment]
> can see all tracks -- as expected.

me too in folder mode

**Comment by wutschel** [comment]
Do we have new information? If not, I would close this one.
