### ISSUE TITLE
Wake On LAN not working since iOS 14.5

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#266]
Reports reach us on the forums [(link to thread)](https://forum.kodi.tv/showthread.php?tid=362316&pid=3033322#pid3033322) that since iOS 14.5 Wake On LAN is not working anymore.

**Comment by wutschel** [comment]
@kambala-decapitator, can you take a look into this?

**Comment by kambala-decapitator** [comment]
yeah, I'll try to investigate

**Comment by wutschel** [comment]
I also read of problems with other Apps connecting to devices (e.g. LINN Kazoo) since iOS 14.5. Is this pointing into the same direction: [iOS 14.5 Beta: UDP broadcast not working with "No route to host" error.](https://developer.apple.com/forums/thread/673062)?

**Comment by kambala-decapitator** [comment]
seems so

**Comment by kambala-decapitator** [comment]
I believe in 14.5 Apple added more restrictions regarding use of multicast addresses. Modern apps must already request special multicast entitlement to be able to use such addresses.

I think the bug can be solved by using LAN's broadcast address instead of 255.255.255.255: https://github.com/xbmc/Official-Kodi-Remote-iOS/blob/master/XBMC%20Remote/AppDelegate.m#L4377

E.g. if target computer's address is 192.168.1.2, then `s_addr` must be 192.168.1.255.

**Comment by kambala-decapitator** [comment]
trying to apply the fix at https://github.com/kambala-decapitator/Official-Kodi-Remote-iOS/tree/fix-wol-14.5

**Comment by anoriega211** [comment]
For what it's worth... that's what the WOL iOS app does, send to the LAN's broadcast, ie 192.168.1.255, address instead of 255.255.255.255, and I saw the WOL packets showing up in wireshark.

**Comment by kambala-decapitator** [comment]
I feel stupid but I don't get how to make the WOL menu item appear in the Remote :D Could someone explain? I've already added MAC address of my Mac running Kodi.

**Comment by anoriega211** [comment]
Assuming on an iPhone, on the page where you select which kodi instance you want to manage, top right should be a power button. Click that and you have Wake On Lan.

If it's ipad, i think it's bottom right there's a power button.

**Comment by kambala-decapitator** [comment]
not sure why, but I don't have it there...

**Comment by joethefox** [comment]
have you selected the host row in the main table before going to the right view (power button)?

**Comment by kambala-decapitator** [comment]
> have you selected the host row in the main table before going to the right view (power button)?

yep, tried that as well, no luck

**Comment by wutschel** [comment]
In case you didn´t still have luck. What worked for me to get the menu entry:
1. Have a Kodi Server in your connection list in the Remote App. Do not connect to it.
2. Ensure this server is switched off before step 3.
3. Start the App and hit the "Power" button (lower right side on iPad).

Now an action sheet should pop up: https://abload.de/img/simulatorscreenshot-i1mk69.png
