### ISSUE TITLE
Feature: Favorites menu

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#268]
Request came via [forum thread](https://forum.kodi.tv/showthread.php?tid=362293&pid=3033819#pid3033819):
Is there a way to have a button to bring you directly to a folder on the home page either under where it says live tv and remote control on the left hand bar , or anywhere else. It would be great if we could have multiple buttons eg button 1 brings you to your new movies folder eg c:\movie\new and button 2 brings you to another folder ge c:\movie\kids etc so that with 1 click you could get to the movie folder you want via a file explorer structure Let the user set the folder themselves, possibly on Kodi first and then mirrored on the app or maybe have a direct link to via the app

**Comment by wutschel** [comment]
First requested in https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/55.

**Comment by kambala-decapitator** [comment]
also requested in appstore review

**Comment by kambala-decapitator** [comment]
one more request from review.

> I’m using the favorites button a lot. When is it missing in the app. Found another remote which is having the remote. So switched over to use the other app now.

**Comment by wutschel** [comment]
First steps done, screenshots:
https://abload.de/img/simulatorscreenshot-ivokx8.png
https://abload.de/img/simulatorscreenshot-i9rjjv.png
https://abload.de/img/simulatorscreenshot-ivoksx.png

1. The app just calls the intended functions and does apply no further logic. This results in favourite albums or folders not being played or opened in the App, but the Kodi server opens the related path in a window. Favorite files will be played and the app switches to NowPlaying screen.
2. Still needs some additional icons (main menu, toolbar and nocover icons). Should be done after the icon rework is finished.
3. Cannot get pictures to be handled properly. For now I throw an error when favorite pictures are selected.
