### ISSUE TITLE
Sort method for addon options

### ISSUE THREAD

**Issue by nikhilk0** [xbmc/Official-Kodi-Remote-iOS#291]
With the latest update, the default sort method for addon options is changed to alphabetically instead of the way intended by the addon.  

![InkedScreenshot (82)_LI](https://user-images.githubusercontent.com/45728234/118370234-6ce38680-b5c4-11eb-9e92-d235eb168fa9.jpg)
![InkedIMG_0027_LI](https://user-images.githubusercontent.com/45728234/118370239-71a83a80-b5c4-11eb-91f9-b46ed021f57d.jpg)

The previous implementation was much better. Is there any way to get that back?

**Comment by wutschel** [comment]
Thanks for your feedback. This might take some time as it is most likely caused by the recently added feature to support "ignore articles". To implement this I needed to change the default way of sorting as well. Is it possible for you to follow the beta versions from TestFlight ([link to forum thread](https://forum.kodi.tv/showthread.php?tid=359717))?

**Comment by nikhilk0** [comment]
No, I can't use testflight as it doesn't work on ios 10 unfortunately. Till the previous stable version, the sorting in app was the same as Kodi.

**Comment by wutschel** [comment]
That´s a pitty, especially because I think I found the issue.

**Comment by kambala-decapitator** [comment]
> No, I can't use testflight as it doesn't work on ios 10 unfortunately.

you're wrong. AppStore asks if you want to download the last compatible version. I've just done that on iPhone 5 and installed Remote from TF.

**Comment by nikhilk0** [comment]
Yeah I can download the last compatible version but when I try to join testing nothing happens. The link redirects me to testflight but remote doesn't get listed. There is loading animation but then nothing. I don't know what's wrong.
I had tried joining 3-4 months ago but wasn't able to join then as well.

**Comment by kambala-decapitator** [comment]
> Yeah I can download the last compatible version but when I try to join testing nothing happens. The link redirects me to testflight but remote doesn't get listed. There is loading animation but then nothing. I don't know what's wrong.
> I had tried joining 3-4 months ago but wasn't able to join then as well.

Please tap on Apple ID in TF app in the bottom and check if there's something wrong. Also please try to logout from your Apple ID (in device's settings) and login again, then try accepting invite once more.

**Comment by nikhilk0** [comment]
> > Yeah I can download the last compatible version but when I try to join testing nothing happens. The link redirects me to testflight but remote doesn't get listed. There is loading animation but then nothing. I don't know what's wrong.
> > I had tried joining 3-4 months ago but wasn't able to join then as well.
> 
> Please tap on Apple ID in TF app in the bottom and check if there's something wrong. Also please try to logout from your Apple ID (in device's settings) and login again, then try accepting invite once more.
> 
Tried this but still not won't let me join.
> I can also add you to TF directly if you provide email address, maybe that helps.
>
I would have tried that had this ipad been not the only apple device I owned. Also, it is a family ipad and other members from my family also use the remote. So, I might stay on stable build especially after TF not allowing me to test the app. Thanks for offering though.
