### ISSUE TITLE
Error when trying to load Music

### ISSUE THREAD

**Issue by cmsimike** [xbmc/Official-Kodi-Remote-iOS#293]
I think from about version 19, whenever I try to refresh the Music library on the Kodi remote, I get
```
XBMC JSON-RPC Error: Internal error.
(Code: -32603)
Data: (null)

METHOD
AudioLibrary.GetAlbums

PARAMETERS
{properties=(year,thumbnail,artist,playcount);sort={"available_methods"={label=(Album,Artist,Year,"Playcount");method=(label,genre,year,playcount);};ignorearticle=0;method=label;order=ascending;};}
```

Other items load fine like movies and TV Shows.

**Comment by wutschel** [comment]
Just adding a link to a forum where this was reported by two users as well: [forum thread](https://forum.kodi.tv/showthread.php?tid=360354).

@kambala-decapitator, @DaveTBlake: Do I understand right that this error message points to is an issue inside Kodi server?

**Comment by kambala-decapitator** [comment]
@cmsimike could you also check / attach Kodi's debug log after receiving the error?

@wutschel can't say tbh. Maybe wrong combination of params?

**Comment by wutschel** [comment]
> Maybe wrong combination of params?

I don´t think so. The parameters shown in the command are the standard parameters which are always used when requesting albums. I am sure this has something to do with the data / music files. 

Independent of this issues I am not sure why the "sort_methods" are sent to Kodi as part of the parameters. As far as I understand the (optional) sort methods are purely handled locally in the App, and the App just requests what it needs via "properties".

**Comment by wutschel** [comment]
> Independent of this issue I am not sure why the "sort_methods" are sent to Kodi as part of the parameters. As far as I understand the (optional) sort methods are purely handled locally in the App, and the App just requests what it needs via "properties".

Did a quick-and-dirty change. This works for reading music albums. I can add this on top of the AppDelegate / Coding Styles PRs as I do not want to implement this twice. Will create an issue to not forget about this.

**Comment by DaveTBlake** [comment]
I would like to see the JSON request that Kodi receives, the "parameters" listed in the post looks odd to me (or at least is an unfamiliar format). A debug log with JSON API component logging enabled should show it. The JSON error codes are useless.

As for why request sorted results, I guess with you are fetching all records and sorting yourself then there is no point, but it would be useful if you wanted just the first 10 e.g. recently played etc.

**Comment by DaveTBlake** [comment]
You realise that GetAlbums, and most (if not all) JSON data requests, the sort method is a single value from List.Sort and not a list of fields e.g. 
```"sort": {"order": "ascending", "method": "year"}```

The screen message in the OP reads like the request had `label,genre,year,playcount`, and that will not work.

**Comment by wutschel** [comment]
> As for why request sorted results, I guess with you are fetching all records and sorting yourself then there is no point, but it would be useful if you wanted just the first 10 e.g. recently played etc.

Agreed. But there is some logic in the App which relies on a default sort already being provided in the JSON response. Maybe this can be removed later, but I´d rather not touch this for now.

> The screen message in the OP reads like the request had label,genre,year,playcount, and that will not work.

And this is the funny part: The Kodi server does not come back with an error in general. The JSON requests include this "available_methods" parameter set since ages. Kodi server seems to just ignore these additional parameters. I am not sure why this was initially implemented like this, and I am already working to remove this.

As I am not sure, if this is causing the problems with Kodi server, I opened https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/294.

**Comment by cmsimike** [comment]
@kambala-decapitator here's the bit relating to the request from the kodi remote app. Let me know if you need the full log but I think this is the most interesting bit

```
2021-05-16 08:28:06.725 T:2927184   DEBUG <general>: ------ Window Init () ------
2021-05-16 08:28:07.459 T:2927184   DEBUG <general>: ------ Window Deinit (Pointer.xml) ------
2021-05-16 08:28:12.354 T:2927912   DEBUG <CWebserver[18080]>: request received for /jsonrpc
2021-05-16 08:28:12.355 T:2927912   DEBUG <general>: connect replacing configured host mysql.example.com with resolved host 192.168.207.247
2021-05-16 08:28:12.615 T:2927912   DEBUG <general>: GetAlbumsByWhereJSON query: SELECT a1.*, album_artist.idArtist AS idArtist, artist.strArtist AS strArtist FROM (SELECT albumview.idAlbum, strAlbum, strArtists, iTimesPlayed, CAST(strReleaseDate AS SIGNED INTEGER) AS iYear, art.url AS thumbnail FROM albumview LEFT JOIN art ON art.media_id = idAlbum AND art.media_type = 'album' AND art.type = 'thumb' WHERE albumview.strReleaseType = 'album' ORDER BY udfNaturalSortFormat(albumview.strAlbum, 8, '.'), udfNaturalSortFormat(albumview.strArtists, 8, '.'), albumview.idAlbum) AS a1 JOIN album_artist ON album_artist.idAlbum = a1.idAlbum JOIN artist ON artist.idArtist = album_artist.idArtist GROUP BY a1.idAlbum, album_artist.idArtist ORDER BY udfNaturalSortFormat(a1.strAlbum, 8, '.'), udfNaturalSortFormat(a1.strArtists, 8, '.'), a1.idAlbum, album_artist.iOrder
2021-05-16 08:28:13.704 T:2927912   ERROR <general>: SQL: Missing result set!
2021-05-16 08:28:13.704 T:2927912   ERROR <general>: GetAlbumsByWhereJSON failed
2021-05-16 08:28:14.841 T:2927184   DEBUG <general>: CheckIdle - Closing session to http://mirrors.kodi.tv (easy=0x7fce1e365400, multi=0x7fce24414a10)
2021-05-16 08:28:15.894 T:2927184   DEBUG <general>: CheckIdle - Closing session to https://mirrors.kodi.tv (easy=0x7fce1db00600, multi=0x7fce226f2d00)
2021-05-16 08:28:16.440 T:2927184   DEBUG <general>: CheckIdle - Closing session to https://mirror.math.princeton.edu (easy=0x7fce26819800, multi=0x7fce2315b000)
2021-05-16 08:28:16.891 T:2927184   DEBUG <general>: ------ Window Init (Pointer.xml) ------
2021-05-16 08:28:17.281 T:2927184   DEBUG <general>: ------ Window Deinit (Pointer.xml) ------
2021-05-16 08:28:18.270 T:2927184    INFO <general>: Stopping player
2021-05-16 08:28:18.270 T:2927184    INFO <general>: Storing total System Uptime
```

As a sanity check, I ran the query in a MySQL window and am getting this:

![image](https://user-images.githubusercontent.com/204378/118403041-70f1c180-b621-11eb-9463-992d95111564.png)

**Comment by cmsimike** [comment]
Digging into it a bit further, it might be an issue with my MySQL server versoin. The Kodi wiki says
> Please use only supported versions of the MySQL or MariaDB server. As of January 2019, this is MySQL in at least version 5.6 or MariaDB in at least version 5.5.

However my server is ` version                  | 8.0.20` so probably not a problem with the Kodi remote app but a problem with the version I'm running having a different version that what the Kodi wiki suggests. It was working until some point however =[

**Comment by wutschel** [comment]
> I would like to see the JSON request that Kodi receives, the "parameters" listed in the post looks odd to me (or at least is an unfamiliar format). A debug log with JSON API component logging enabled should show it. The JSON error codes are useless.

Well, the format is a bit weird. The command related to the issue would read like:

`{"properties": ["year", "thumbnail", "artist", "playcount"], "sort": {"available_methods": {"label": ["Album" ,"Artist", "Year", "Play count"], "method": ["label", "genre", "year", "playcount"]}, "ignorearticle": false, "method": "label", "order": "ascending"}}`

As you already checked that the `available_method ` key is ignored in Kodi server this melts down to:

`{"properties": ["year", "thumbnail", "artist", "playcount"], "sort": {"ignorearticle": false, "method": "label", "order": "ascending"}}`

Quite simple request I would say.

**Comment by DaveTBlake** [comment]
@cmsimike you have an MySQL/MariaDB issue as shown by 
`ERROR <general>: SQL: Missing result set!`

Not a problem that MySQL is different from that listed in the wiki, but a settings issue. Search the Kodi Forum for "SQL: Missing result set" and solutions are provided.

**Comment by cmsimike** [comment]
@DaveTBlake Thanks for the suggestion. 
I tried modifying the mysql config file to `sort_buffer_size=50M` however it did not solve my problem. I still have the same issue. 
I really do think the issue is the MySQL error. The SQL query doesn't complete even outside of the remote. The MySQL query does not return any results because of (what my MySQL server thinks) is a problem with the query itself:

> Expression #6 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'a1.thumbnail' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by DaveTBlake** [comment]
@cmsimike running that query on my installation of MySQL works fine. Also when the query syntax is the issue we get different things in the Kodi log file from "SQL: Missing result set". 

Perhaps sql_mode is the issue?  I don't think it is `only_full_group_by` by default, at least I don't have that mode set. Use 
```
 SELECT @@sql_mode;
```
to return current mode values, and then similarly use  `SET sql_mode` to set it to the values you get less only_full_group_by`.

Mine is set `STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`
 so assuming those settings are what we want (I don't no more than it works and it was like that by default)
```
 SET sql_mode = 'STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`;
```

**Comment by cmsimike** [comment]
@DaveTBlake Sorry if I implied that the syntax is the issue - it isn't. But as you mentioned it definitely has someting to do with the sql_mode. My mode has `ONLY_FULL_GROUP_BY` in it, so I removed it:
`ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION`
Now I'm running into a different issue:

> [22001][1406] Data truncation: Data too long for column 'sortString' at row 1

I tried setting your specific mode however that caused MySQL not to start:
> 2021-05-16T18:12:17.138020Z 0 [ERROR] [MY-000077] [Server] /usr/sbin/mysqld: Error while setting value 'STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' to 'sql_mode'.

If this is starting to get off topic, I'm happy to close this/move it elsewhere.

**Comment by cmsimike** [comment]
FYI I am seeing a similar issue here: https://forum.kodi.tv/showthread.php?tid=361905 so I'm going to read through this and see if anything jumps out at me. Thanks for all the help so far.

**Comment by cmsimike** [comment]
Oh hey you're commenting in this thread!

**Comment by cmsimike** [comment]
Long story short, looks like a fix will be available on v20. https://github.com/xbmc/xbmc/pull/19635

i did a query on my album titles and don't have any long `strAlbum`s so not sure why my specific case is failing. But long story short, my specific issue now seems to be outside of the context of the kodi remote.

Thanks for all your help so far! There was other discussion above so if you want to keep this issue open for that, please do but as for the original reason for opening this issue, it isn't an actual issue with the kodi remote.

**Comment by wutschel** [comment]
> There was other discussion above so if you want to keep this issue open for that, please do but as for the original reason for opening this issue, it isn't an actual issue with the kodi remote.

A new issue was opened for the other discussed topic. Imo there is so need to keep this one open.

**Comment by DaveTBlake** [comment]
> Long story short, looks like a fix will be available on v20. xbmc/xbmc#19635

That has also been backported to v19.1 @cmsimike, but existing MyMusic82 databases will need a manual intervention. Anyway, not for this issue or repo. Please start a thread on [Music support subforum](https://forum.kodi.tv/forumdisplay.php?fid=263) for any further discussion, I'm happy to follow this up to a resolution.

**Comment by marlemion** [comment]
So this bug has not been fixed in 19.4 even if allegedly backported as tagged here: https://github.com/xbmc/xbmc/pull/19635

I had this problem with the Kodi remote app on IOS on the iphone of my girlfriend. Yatse on Android had no problem at all. I have a big Music collection and Kodi remote was not able to access the database anymore. As my girlfriend uses this option very rarely, it didn't surface until recently. So I dug into the forums and understood that the fix here should have been backported. I apparently had to rebuild the music db from scratch, what I did: removed the db from the mysql server, restarted Kodi and rescanned the source.

Didn't help. Same message as in the original post here. So nofix for 19.4. Can anybody confirm that the fix has not been backported? Otherwise the fix might not be universal.

Recent arch, kodi 19.4, mariadb 10.8

**Comment by wutschel** [comment]
As far as I can see on GitHub the backport to Matrix was done on 2021, May, 1st. It was part of Matrix releases since 19.1. I cannot comment if any later change broke this. You say you see the same message as in the first post in this thread. Really the same, or just the upper part? I am asking as the JSON command sent by the iOS Remote should look different since many releases. Your description points to a Kodi server internal error which is triggered by a certain _parameter_ / _properties_ set of the JSON API method _AudioLibrary.GetAlbums_.

I am sure the following will be of help:
1. Can you share Kodi logs which show JSON command / response, SQL and the error? 
2. Can you also share a log on how JSON command / response and SQL behaves when using Kore?

**Comment by wutschel** [comment]
Well, until the database having music I cannot really help with looking into differences of the iOS and Android remote commands. I am not sure why adding sources and scanning them does not add the music to the database.

**Comment by marlemion** [comment]
Well, unfortunately, the database **is** filled with albums, artists etc. I can confirm that by directly looking at MyMuisc82, e.g. using phpmyadmin.

**Comment by wutschel** [comment]
Sorry, then I misunderstood your statement "but in Kodi no Music". So, at low-level you can see the DB content, but neither Kodi itself, nor the remote app shows any content. Is this right?

**Comment by marlemion** [comment]
Yes, indeed. I dug into the logs and found this:

```
 ERROR <general>: SQL: [MyMusic82] The table does not exist
                                                   Query: select count(idSong) as NumSongs from songview
```

Indeed, the *view tables are missing from the database. I have googled a bit. There are a few very old posts about this and even a script to build a respective DB having the tables. Do you have any idea why kodi leaves out the *view tables?

**Comment by wutschel** [comment]
No, sorry. I am only working on the remote app itself and have no insight to this. Maybe @DaveTBlake can comment?
