### ISSUE TITLE
Maintenance: @"available_methods" sent as part of JSON command

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#294]
The App uses a dictionary named `"available_methods"` to handle the different sort methods and sort method names. In its current implementation the dictionary is even sent to Kodi server as part of the JSON command when e.g. requesting an album list. To my knowledge this is not causing any problems, but also is not needed as the whole sort implementation is -- besides the initial JSON command to Kodi server -- handling sorting locally.

Below screenshot shows the current JSON command (red) to retrieve an album list. It includes the "available_methods" dictionary. The second JSON command (green) is the same without this dictionary. The list is still received as expected and sorting is possible after a few code changes. (Remark: I created a quick-and-dirty faulty JSON command with adding a leading "1" to "properties" to let the popup show.).
 
<a href="https://abload.de/image.php?img=bildschirmfoto2021-05ynk8c.png"><img src="https://abload.de/img/bildschirmfoto2021-05ynk8c.png" /></a>

**Comment by wutschel** [comment]
This change (mainly parameter definition) does the trick: https://github.com/wutschel/Official-Kodi-Remote-iOS/commit/ab348829688bc65739aa8c152572a3ced2216308 

Will wait until the PRs got merged which are the base of this change.

**Comment by DaveTBlake** [comment]
> To my knowledge this is not causing any problems,

It is luck that JSON requests with "available_methods" as parameter of "sort" does not fail. The "method" parameter should also be a single enum value and not a list.

**Comment by wutschel** [comment]
It is irritating the App was requesting in this faulty way like ages ...

A sort request should look like marked in the green box, correct? `sort={ignorearticle=0;method=label;order=ascending;}`

**Comment by DaveTBlake** [comment]
I am not used to seeing requests with `=` and `;`  but otherwise yes, single method value
```
"sort": {"order": "ascending", "method": "artist", "ignorearticle": true}
```
 It does seem that Kodi is currently ignoring that extra "available_methods" in the sort parameter, but that is not by design. Really the JSON implementation should reject it as a malformed request, hence me saying it works by luck. I don't have any plans to fix the JSON parameter validation, but someone could do one day.

**Comment by wutschel** [comment]
Thanks for confirming. I will definitely clean this up.
