### ISSUE TITLE
volume +/- buttons not working/disabled  on iPhone5

### ISSUE THREAD

**Issue by howie-f** [xbmc/Official-Kodi-Remote-iOS#295]
iOS 10.3.4 - remote v1.7 (2316)

the slider in blue looks a bit inconsistent as it is grey on the now playing screen

![IMG_3898](https://user-images.githubusercontent.com/58829855/118394441-136f6c00-b645-11eb-86b9-9c744e5087f2.PNG)

**Comment by wutschel** [comment]
The buttons were re-enabled with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/288 already. This did not make it in the 1.7 release, but will be part of next update.

The slider was always blue, for consistency I just also made the thumb blue now. The NowPlaying progress bar will assume the color given by the album/movie/thumb average color. If such color cannot be derived, it will also show the same blue. But I have no strong opinion on this. The blue color at least highlights the slider very well.

**Comment by howie-f** [comment]
ah yes, thanks for the info @wutschel - the color of slider doesn‘t really bother ;) closing then
