### ISSUE TITLE
Feature: Open with VLC 

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#299]
There is a feature prepared in the App´s source code to open certain content with VLC. This option can be given in action sheets. Currently the actions are commented and therefore not selectable in the UI. The code for the feature itself is active and needs some refactoring due to code duplication (`openWithVLC` in `DetailViewController` and `ShowInfoViewController`).

1. Shall the whole feature be removed or enabled or stay disabled for now?
2. Shall a #define be added to switch on/off the feature at compile time?

**Comment by kambala-decapitator** [comment]
1. as long as nobody requests it, can stay disabled. Removing is also an option.
2. you can implement it and disable by default if you wish :)
