### ISSUE TITLE
SongDetails view does not always show artist information

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#303]
The artist information in the SongDetails view is only shown when the playback is triggered from Kodi server. When triggering the playback via the remote this information is not displayed. Tested with Kodi 20 Alpha.

Screenshot:
https://abload.de/img/bildschirmfoto2021-05ikj4b.png

**Comment by wutschel** [comment]
This could also be an issue with Kodi server itself. The JSON command (`"Player.GetItem"`) always uses the same properties:

```
{"properties": ["album", "artist", "title",  "thumbnail", "track", "studio", "showtitle", "episode", "season", "fanart", "description", "plot", "art"]}
```

In the case where the artist info is not shown the response just misses the key `"description"`.

**Comment by DaveTBlake** [comment]
I think I may have a related long standing WIP @wutschel, nothing to do with JSON. There are at least 6 different ways to initiate play back of a song (or list of songs), all of them take different routes through the code. That alone is a bit bonkers and hard to maintain, but history got us there. Some routes ensure that additional artist data for the song artist is loaded, others do not. When this extended data for the item not loaded neither UI or JSON Player.GetItem have access to it.

So if the question was why don't we always get artist biography for the currently playing song, only sometimes, then the answer is that inconsistent implemention deep inside Kodi core. It isn't an easy one to unpick without breaking something (or even everything!), and really needs a fundamental redesign, but it is high on my list for v20.

As for the JSON part, Player.GetItem is a little messy anyway. What properties an item has depends on what type of thing the item is, and that variation is not captured in the schema.  But for sure inconsistent results for a item type is far from ideal.

**Comment by wutschel** [comment]
Ok, seems to be a bit more complicated, and not related to the Remote App. I will close this then.
