### ISSUE TITLE
Feature: Configurable main menu

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#306]
I think of adding an option to hide unneeded main menu items. On iPad this can give more space for the playlist item, and overall it does reduces the menu to the functions important to the user.

<a href="https://abload.de/image.php?img=bildschirmfoto2021-05l4ky4.png"><img src="https://abload.de/img/bildschirmfoto2021-05l4ky4.png" /></a>

**Comment by kambala-decapitator** [comment]
nice idea! Kodi spirit :)
