### ISSUE TITLE
Feature: hiding movie sets with only one movie

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#308]
Feedback from TF:

> Just dipped into movie sets, and though hiding movie sets with only one movie is enabled within Kodi, the remote app doesn’t honor that. Please add this feature!

**Comment by wutschel** [comment]
Is there a feature flag which can be checked via JSON API? Or is the idea to always hide movie sets with only a single movie?

**Comment by wutschel** [comment]
Hmm, in the API spec I see no parameter for `VideoLibrary.GetMovieSets` which returns back how many movies are in a collection. This makes it a bit complicated to check the condition. For each collection a new JSON command would need to ask for the movies.

**Comment by wutschel** [comment]
> Is there a feature flag which can be checked via JSON API?

@DaveTBlake, I can see a feature switch for this. Could you point me to the place where I can find out how to read the setting via the JSON API?

> This makes it a bit complicated to check the condition.

Did a first implementation for this feature in https://github.com/wutschel/Official-Kodi-Remote-iOS/commit/bc9932e748ce109186bb4efd72429a1fe014a3ff. I added a special treatment only for movie sets: For each movie set the amount of movies in this set is checked via a new JSON request. If more than 1 movie is in the set, this set is added to the result list. Only when the check for the last movie set was done, the list is saved and presented.

Screenshots:
https://abload.de/img/simulatorscreenshot-if0kuw.png (before)
https://abload.de/img/simulatorscreenshot-ih9kbk.png (after)

Nevertheless I would definitely prefer to have the amount of movies reported via JSON as result of `VideoLibrary.GetMovieSets`.

**Comment by wutschel** [comment]
> Is there a feature flag which can be checked via JSON API?

Found it. This feature flag can be read via `Settings.GetSettingValue` with parameter `{"setting": "videolibrary.groupsingleitemsets"}`.
