### ISSUE TITLE
Feature: Update icons to Kodi 19

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#310]
In the past days I was working on updating the main buttons/icons/logos to Kodi 19. I am not yet fully convinced of all the details but wanted to share some impressions. Comments are highly welcome!

DayMode:
https://abload.de/img/simulatorscreenshot-iltjfm.png (Main Menu)
https://abload.de/img/simulatorscreenshot-ivxjqp.png (Music Menu)
https://abload.de/img/simulatorscreenshot-i4wk5h.png (Music Genres)
https://abload.de/img/simulatorscreenshot-irpky9.png (Music "More")
https://abload.de/img/simulatorscreenshot-i1xjw9.png (Movies Menu)
https://abload.de/img/simulatorscreenshot-ihdj9w.png (Movie Genres)
https://abload.de/img/simulatorscreenshot-i8uj10.png (Movies "More")
https://abload.de/img/simulatorscreenshot-icwkfc.png (TVShow Menu)
https://abload.de/img/simulatorscreenshot-inkk3f.png (Pictures Menu)
https://abload.de/img/simulatorscreenshot-irvkfk.png (LiveTV Menu)
https://abload.de/img/simulatorscreenshot-idgj43.png (Live TV Menu, grid view)
https://abload.de/img/simulatorscreenshot-irmjpl.png (Settings Menu)
https://abload.de/img/simulatorscreenshot-idxjjo.png (List of music files)
https://abload.de/img/simulatorscreenshot-igwju1.png (List of movie files)
https://abload.de/img/simulatorscreenshot-iyhjob.png (List of images files)
https://abload.de/img/simulatorscreenshot-i0ajao.png (List of actors)

DarkMode:
https://abload.de/img/simulatorscreenshot-i2ij1s.png (List of images files)
https://abload.de/img/simulatorscreenshot-iyckhz.png (Music Genres)
https://abload.de/img/simulatorscreenshot-ibtk4c.png (Music "More")
https://abload.de/img/simulatorscreenshot-ij2je3.png (Movie Genres)
https://abload.de/img/simulatorscreenshot-i6yjkm.png (Movie Sets)
https://abload.de/img/simulatorscreenshot-iq7j9g.png (Movies "More")

**Comment by howie-f** [comment]
just a comment on https://abload.de/img/simulatorscreenshot-irvkfk.png
imo, what now is the "remote control" on the left can maybe look more like a tv-screen/monitor / for the recordings icon i think the old "circle" style is more intuitive because it looks similar to the gui record button... my 2 cents
anything else looks nice, nothing to worry about

**Comment by wutschel** [comment]
Valid points. I was wondering if young users would even relate the cassette icon to recordings (I like it though). Maybe this is a bit too much retro style. :)

**Comment by wutschel** [comment]
Few options:
https://abload.de/img/simulatorscreenshot-irvkfk.png
https://abload.de/img/simulatorscreenshot-ijrjrr.png
https://abload.de/img/simulatorscreenshot-i99j2q.png

I also must say I like the last one most. Not fully Kodi 19, but symbols which are simple and easy to understand.

**Comment by wutschel** [comment]
Few more changes:
https://abload.de/img/simulatorscreenshot-iejjlf.png (Movie Sets have a "nocover" icon as well now)
https://abload.de/img/simulatorscreenshot-ibsjvl.png (Video and Audio AddOns have new icons)
https://abload.de/img/simulatorscreenshot-i32jqm.png (Updated icons for update/clean library)

**Comment by wutschel** [comment]
Updated remote and help screen:
https://abload.de/img/simulatorscreenshot-iobjjf.png (remote iPad)
https://abload.de/img/simulatorscreenshot-i5bj6b.png (remote help iPad)
https://abload.de/img/simulatorscreenshot-i7oksv.png (remote iPhone)
https://abload.de/img/simulatorscreenshot-i2ajh7.png (remote help iPhone)

Not sure, if the icons on the buttons should be gray instead of white. Also it might look nice to have round edges for the button background. But overall this no matches the look of the other updated icons.

**Comment by wutschel** [comment]
Less aggressive (gray) colors, and updated "toggle display" icon:
https://abload.de/img/simulatorscreenshot-i4qkgx.png (remote iPhone)

**Comment by wutschel** [comment]
Few more updates:
https://abload.de/img/simulatorscreenshot-i41jww.png (updated remote logo)
https://abload.de/img/simulatorscreenshot-iiyjwl.png (updated logo to switch to remote on upper right side)
https://abload.de/img/simulatorscreenshot-i0gjkp.png (remote with updated background - coming from now playing screen)
https://abload.de/img/simulatorscreenshot-i7xker.png (remote with updated background - coming from main menu)
https://abload.de/img/simulatorscreenshot-ih8kni.png (remote help screen)

**Comment by wutschel** [comment]
Now even fully reworked remote help and gesture view to use a modern font:
https://abload.de/img/simulatorscreenshot-ib5j8p.png
https://abload.de/img/simulatorscreenshot-idkj8m.png
https://abload.de/img/simulatorscreenshot-iv5kec.png
https://abload.de/img/simulatorscreenshot-itbkel.png
