### ISSUE TITLE
1.7.1 crash reports

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#323]
@wutschel you're welcome to investigate :)

[AppStore.tar.gz](https://github.com/xbmc/Official-Kodi-Remote-iOS/files/6621904/AppStore.tar.gz)

**Comment by wutschel** [comment]
> One more crash refers again to our good old friend `presentViewController`.

I found 3 potential areas of interest. Let´s see if this finally resolves this issue. At least the other "good friend" `pushViewController` was not showing up so far.

**Comment by wutschel** [comment]
> Then there is a line referenced multiple times, but I cannot see any problem with it (2nd line produces the crash):

Got it. :)
