### ISSUE TITLE
Always connects to port 80 when it is behind a proxy.

### ISSUE THREAD

**Issue by hnws** [xbmc/Official-Kodi-Remote-iOS#33]
I have a local squid proxy.
iPhone is set up to use the proxy in wifi settings.
When I am trying to connect to 8080 port, squid always got below request.

14 192.168.1.157 TCP_MISS/400 378 POST http://192.168.1.160/jsonrpc - HIER_DIRECT/192.168.1.160 text/html

Within same network under the same proxy configuration, other systems work fine.

**Comment by wutschel** [comment]
@kambala-decapitator, is this something you would be able to check? I am not sure, if this is anyway outdated.

**Comment by kambala-decapitator** [comment]
never used proxies, also no other request about it, let's close
