### ISSUE TITLE
1.8 release notes

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#357]
Let's start preparing next release.

@wutschel could you add release notes?

Btw should we call the next version 1.7.2 or 1.8?

**Comment by wutschel** [comment]
Sure, I will provide a draft for the release notes. I think 1.8 is matching better to what was done. The App really looks different compared to before with all the new icons and rounded corners.

**Comment by wutschel** [comment]
We should update the screenshots for the AppStore when we update to the new version. It really looks different now. I can provide some for both iPad/iPhone and and upload them. Is there a specific resolution or model required, or is this simply the native resolution when using the simulator's "save screen" function?

**Comment by kambala-decapitator** [comment]
would be great if you could provide them!

we need at least the following sizes:

1. iPhone 6.5''
2. iPhone 5.5''
3. iPad 12.9''

please consult apple docs to determine the right device.

> simply the native resolution when using the simulator's "save screen" function

this
