### ISSUE TITLE
Rounded corners impacts automatic background for TV station logos

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#366]
Reported in [this forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3055203#pid3055203). For some TV station logos a different background color is selected. The code which causes this:

```
...
CGRect imageRect = CGRectMake(0, 0, image.size.width, image.size.height);
UIGraphicsBeginImageContextWithOptions(image.size, NO, 1);
// Get image and cleanup
UIImage *roundedCornerImage = UIGraphicsGetImageFromCurrentImageContext();
UIGraphicsEndImageContext();
return roundedCornerImage;
```

Simply returning `image` instead of the freshly created `roundedCornerImage` fixes the problem.

**Comment by wutschel** [comment]
@kambala-decapitator, can you give me a hint where to look at? For now I checked the colorSpace, which is same.

**Comment by wutschel** [comment]
The difference is that `kCGBitmapByteOrder32Little` is set for the newly create image. The original one uses `kCGBitmapByteOrderDefault`.

**Comment by kambala-decapitator** [comment]
> The difference is that `kCGBitmapByteOrder32Little` is set for the newly create image. The original one uses `kCGBitmapByteOrderDefault`.

sorry, such stuff is above my knowledge

**Comment by wutschel** [comment]
The fix seems simple. I already implemented re-formatting into the desired image format. But I was not taking into account the byte order as I was masking only for the alpha-format. I just need to remove the mask and check the unmasked format against the desired one.

https://github.com/wutschel/Official-Kodi-Remote-iOS/tree/fix_background

**Comment by kambala-decapitator** [comment]
I trust you :)

**Comment by wutschel** [comment]
In fact, the "rounded corners" feature was just showing a gap in the code which analyzes the average color. Best will be to get the fix into one of our next beta builds and ask for tests.
