### ISSUE TITLE
Low resolution artist and album thumbnails

### ISSUE THREAD

**Issue by warwickmm** [xbmc/Official-Kodi-Remote-iOS#394]
**Remote version:** 1.8 (2615)
**Device**: iPad Air 2 and iPhone 12 mini running iOS 15
**Kodi version:** 18.2 (LibreElec 9.2)

After upgrading to version 1.8, the thumbnails in the artist and album lists were replaced with low quality versions.  The thumbnails in the playlist and album track view remain high quality.   Previously, all thumbnails were of high quality.  The album art comes from a local `cover.jpg` file.

In the below screenshot, compare the album thumbnails in the playlist (left, clear), album list (middle, blurry), and album track view (right, clear):

![remote](https://user-images.githubusercontent.com/17345532/134706870-68fab9a5-61b3-4201-b988-1e2e9af18c8f.jpg)

The thumbnails in the artist list, as well as those when viewing the albums by artist are also low resolution.

**Comment by warwickmm** [comment]
Here's a zoomed in version to help illustrate the differences:

![image](https://user-images.githubusercontent.com/17345532/134710656-71955253-ae17-4496-bdd6-6a58508827ea.png)

**Comment by wutschel** [comment]
Is this the same when you deactivate rounded corners in the app settings?

**Comment by wutschel** [comment]
> Is this the same when you deactivate rounded corners in the app settings?

Confirmed. This is independent of enabling rounded edges or not and came in with build 1.7.2-b8. I am looking into this now.

**Comment by wutschel** [comment]
Found and fixed this. Thanks for pointing this out!

**Comment by warwickmm** [comment]
Thanks for the quick fix!
