### ISSUE TITLE
Feature: Ideas on new features around TV Shows (from AppStore user)

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#399]
Idea is to add some ways to easier queue TV Shows. 2 features would be great:

1. Long press on TV Show Season to open a menu with ‘Play all (in sequence)’ which plays all of the episodes in the correct order. Would be good if it also had ‘Play all (random)’.

2. When viewing TV Show episodes list, would be good to have checkboxes on the left. Add a button for ‘Play episodes’ so users can play the selected episodes they want.

**Comment by wutschel** [comment]
The first idea -- "Play all (in sequence)" -- I really like. Somehow this is in line with how music albums are played. Playing random can be achieved by simply enabling shuffle once the playback started. I am not convinced this should be selectable right from the start.

I am aware that it requires more steps to remove items from the playlist or add the episodes one after the other. But still I personally find the second idea a too specific use case.

**Comment by JUSSKiE** [comment]
Hi wutschel,

I was the AppStore user :) thanks for taking the time to add this to github. I just wanted to clarify how the idea came about. I have 2 daughters and they're obsessed with The Simpsons and it's one of those TV Shows that you can just watch again and again and again - and we really do lol. 

So I thought it would make sense to be able to watch a whole season easily so I don't have to continually queue up episodes. Having the random episode option would be good especially for this TV Show but I understand it may be a bit too specific.

Thanks

**Comment by wutschel** [comment]
Hi @JUSSKiE,

good to see you here. I will try to look at this once we are clear with the issues from last release and the already prepared new features.

Thanks for sharing your suggestion!

**Comment by wutschel** [comment]
Today I found some time to look into this feature. I am not 100% satisfied as you cannot long press on a season to trigger playback, but you can long press on an episode and then process from there. I added the option to play all episodes of the TV show or all episodes of the season. I could add a function to play all TV show episodes from the details info view as well. The code is not finalized and I am not sure if the sorting is always right, but it basically works.

First impression: https://abload.de/img/simulatorscreenshot-inikbq.png

**Comment by wutschel** [comment]
Recently made some good progress on this. I prepared a change to introduce a long press option for seasons which allows to watch/unwatch a whole season and added "Queue", "Queue after current" and "Play" of a whole season. The App will simply queue/play them in the order reported back from Kodi.

**Comment by wutschel** [comment]
Long press season can be tested on a TF build (see [TF build 4253.42](https://forum.kodi.tv/showthread.php?tid=359717&pid=3185536#pid3185536), available next 90 days). It supports Play, Queue, Queue after current and Mark watch/unwatch. Shuffle can be enabled via NowPlaying screen.
