### ISSUE TITLE
RFC Add option to use volume buttons to send volume up/down to CEC/XBMC

### ISSUE THREAD

**Issue by tudstudent** [xbmc/Official-Kodi-Remote-iOS#40]
As might be known, constellation has the option to send volume actions to XBMC (CEC off) or to CEC device (CEC option on).

It would be nice if this could be added to this great app. Currently this feature I am missing very badly.
Thanks.

**Comment by wutschel** [comment]
Kodi API does not offer sending CEC volume commands. Without changes to Kodi itself this cannot be implemented.

@kambala-decapitator, should we close this?

**Comment by kambala-decapitator** [comment]
#5
