### ISSUE TITLE
Not connecting to Kodi 11 since App version 1.6.2

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#405]
While working on crashes reported with App version 1.8 I tried to play around with the older supported Kodi/XBMC version 11. Obviously this version is not supported anymore since App version 1.6.2 as since then a change was introduced which causes the App to crash always. This can be fixed pretty easily with a simple change when reading the API version.

Another option is to drop the support for XBMC 11 and clean up the related code. There are many places where the server version is checked for version 11 (>, <, >=, <=, ==).

**Comment by wutschel** [comment]
Fix: https://github.com/wutschel/Official-Kodi-Remote-iOS/commits/fix_xbmc_eden

**Comment by phunkyfish** [comment]
I would think that cleaning up the code and only supporting Leia/Matrix/master would make sense.

Then we support Python2/3 and those who can’t or don’t want to move to Matrix have an upgrade path. Just my opinion though.

**Comment by wutschel** [comment]
I don´t think it is required to limit the support this much. When dropping version 11 aka Eden >80% of the version checks become obsolete. I am just proposing this as version 11 support is broken since more than half a year and there were no complaints.

**Comment by phunkyfish** [comment]
Ok, then I would just drop support for 11 😉

**Comment by wutschel** [comment]
Remove Eden support: https://github.com/wutschel/Official-Kodi-Remote-iOS/tree/drop_eden

**Comment by wutschel** [comment]
@kambala-decapitator, for now I tend towards fixing the support for Eden. This matches the current advertised and documented support. Also, this avoids crashes when attempting to connect to such versions.

At a later point in time we can decide to remove the support for Eden to reduce the complexity.

**Comment by kambala-decapitator** [comment]
> This can be fixed pretty easily with a simple change when reading the API version.

since the fix is easy, why not

**Comment by wutschel** [comment]
PR for fixing is raised. Cleanup can be done with a later release then.
