### ISSUE TITLE
iOS 15 UI glitches when compiled with XCode 13

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#411]
Since iOS 15 SDK (XCode 13.0) there are some glitches in the UI which need some attention.

1. Some padding above sections: https://abload.de/img/bildschirmfoto2021-1040jq8.png
2. Navigation Bar is transparent (should be translucent and blurred): https://abload.de/img/bildschirmfoto2021-10pik2s.png

**Comment by kambala-decapitator** [comment]
ASC started spitting out new warning (non-blocking):

We identified one or more issues with a recent delivery for your app, "Official Kodi Remote" 1.10 (2939). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90901: Missing full-screen support for the latest iPad mini display. The “Kodi Remote.app” bundle includes UIRequiresFullScreen=YES in the Info.plist or supports only a subset of UISupportedInterfaceOrientations, and is built with the 14.5 SDK. To take advantage of the full screen size, recompile with Xcode 13 and the SDK for iPadOS 15 or later.

**Comment by wutschel** [comment]
> ITMS-90901

Do I understand correct that we do not need to fix anything in the app, but just build the release with the latest Xcode version?

When I look at `UISupportedInterfaceOrientations` I am wondering why we only defined 3 orientations for iPhone (_"Portrait (top home button)"_ is missing) and all 4 for iPads. Should the 4th orientation be added as well?

<a href="https://abload.de/image.php?img=bildschirmfoto2021-127yjto.png"><img src="https://abload.de/img/bildschirmfoto2021-127yjto.png" /></a>

**Comment by kambala-decapitator** [comment]
> Do I understand correct that we do not need to fix anything in the app, but just build the release with the latest Xcode version?

Yes, no action needed.

> When I look at `UISupportedInterfaceOrientations` I am wondering why we only defined 3 orientations for iPhone (_"Portrait (top home button)"_ is missing) and all 4 for iPads. Should the 4th orientation be added as well?

That's a traditional approach to exclude upside down orientation on the iPhone. Can be added as well, I have nothing against it.

**Comment by wutschel** [comment]
> That's a traditional approach to exclude upside down orientation on the iPhone. Can be added as well, I have nothing against it.

Ok, then let's keep it like it is.
