### ISSUE TITLE
Appstore feedback: sort/filter issues

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#414]
Merci pour cette nouvelle version. Je me permets de vous informer qu'il y a quelques bugs embarrassants. Il est impossible de faire un filtre dans l'onglet films en mode vignettes et on ne peut pas faire de tri quand on fait un filtre par genre.

Thank you for this new version. Let me inform you that there are some embarrassing bugs. It is impossible to make a filter in the films tab in thumbnail mode and you cannot sort when you filter by genre.

**Comment by wutschel** [comment]
Thanks for sharing. If I understand right the requests are to
1. Filter/search when in grid/wall view mode. This is not a bug, it is not implemented and it never was. Older versions (before 1.6) fell back to list view in this case. The current version just shows an information to switch to list view.
2. Apply any sort order when in genre view. This seems to be a bug and came in with 1.8. I will look into this.
