### ISSUE TITLE
Feature: Skip Steps to be configurable

### ISSUE THREAD

**Issue by Tony-Coding** [xbmc/Official-Kodi-Remote-iOS#427]
I posted the below question in another forum and thought it would be a good feature request. To alter the behaviour of the Skip Steps. I use +3min as it gets pretty close to the end of the commercial and I can back track 10 seconds each press.

1. Skip Steps to use the configured values in Kodi. This is difficult as Buschel advises below.
2. Make Skip Steps configurable in the Kodi App.
3. Don't have the app handle the seek rather. The App sends the UI navigation command ("navigate right") and Kodi server handles the seek (as if the i button was pressed) I gleaned this from Buschel's comment and don't know if it is possible .

Thanks
Tony

[https://forum.kodi.tv/showthread.php?tid=364635&pid=3064299#pid3064299](url)
I notice that when I press the navigate right or navigate left buttons on the Remote. It skips 30 seconds.
When I press the show information button 'i' which displays the time slider on the tv it will skip as per my setup skip steps in Kodi. (Ie. +3 min, +5 min, +10 min, -30sec, -1min, -10min)
Is there a way to have the navigate right and navigate left buttons skip as per the kodi skip steps, without having to press the 'i' ?

Buschel replied with:
I just took a look into the App's source code. When the (i) button was pressed and the time bar is shown the App does not handle the seek anymore. The App only sends the UI navigation command ("navigate right") and Kodi server handles the seek. When the time bar is not shown the App sends "seek" commands which always uses +/-30 seconds or +/- 10 mins. To implement what you are having in mind, the App would need to read the Kodi server settings for seek steps and use them for the seek commands. I am not yet sure, if reading the seek step is supported by Kodi's API. In addition, this will be requiring quite some changes in the seek handling on the App's side. So: Not sure, if feasible, and not a simple change to do.

**Comment by wutschel** [comment]
Thanks, good to see your input here. I will have a look at this at a later point in time. First, a lot of other changes are prepared and shall go into the Remote App.

**Comment by wutschel** [comment]
Finally changed this now, see the PR for more details.

**Comment by Tony-Coding** [comment]
Great to hear, thanks, I can't wait to try it out. Thanks for the update.
