### ISSUE TITLE
Special treatment for PVR recordings causes loss of features

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#430]
### Background:
The Remote App`s playback concept is playlist centric. When requesting to play an item the Remote App will first add the item to the playlist, and then play the playlist. This allows to queue more items either right after the current playing item or at the end of the playlist. A simple direct playback of any item will violate this basic concept and would cause problems, e.g. not being able to queue items right after current playing.

### Problem:
Until the current Kodi version 19.1 there is no support for `recordingid` in `Playlist.Add` and `Playlist.Insert`. To work around this any `recordingid` item will be added as `file` to the playlist. This causes the function `Playlist.GetItem` to not being able to resolve thumbnails, icons, descriptions or plots. In consequence the NowPlaying screen will no show such existing (!) metadata.

Another problem is that `playcount` is only updated on the JSON API when a recording is played via `recordingid`. If a recording is played via its `file` path (e.g. `pvr://path-to-recording`), the `playcount` Kodi-_internally_ is increased but it is not changing on the JSON API. Example:
1. play via `file` -> JSON API `playcount=0`
2. play via `recordingid` -> JSON API `playcount=2`
3. play via `file` -> JSON API `playcount=2`
4. play via `file` -> JSON API `playcount=2` 
5. play via `recordingid` -> JSON API `playcount=5`

### Solution:
The proper solution will be to support `recordingid` in `Playlist.Add` and `Playlist.Insert` in Kodi and remove Remote App`s special treatment from then on.

### Alternative:
Also use direct playback (like for Live TV channels). In this case you cannot enqueue recordings, and enqueuing any other item "after the current item" will place this as the start of the playlist.

### Screenshots:
Current look caused by playing `file` type:
<a href="https://abload.de/image.php?img=simulatorscreenshot-ighj8c.png"><img src="https://abload.de/img/simulatorscreenshot-ighj8c.png" /></a> <a href="https://abload.de/image.php?img=simulatorscreenshot-i1okxx.png"><img src="https://abload.de/img/simulatorscreenshot-i1okxx.png" /></a>

If playing via `recordingid`:
<a href="https://abload.de/image.php?img=simulatorscreenshot-ik2kfa.png"><img src="https://abload.de/img/simulatorscreenshot-ik2kfa.png" /></a> <a href="https://abload.de/image.php?img=simulatorscreenshot-i6cjiy.png"><img src="https://abload.de/img/simulatorscreenshot-i6cjiy.png" /></a>

**Comment by wutschel** [comment]
@ksooo, do you maybe have an idea how to tackle this?

**Comment by howie-f** [comment]
sorry for the delay wutschel, turns out it‘s not as simple as just extending Playlist.Item.. honestly i‘m stuck at the moment 🤔

**Comment by wutschel** [comment]
No worries, and thanks for taking a look at this.

**Comment by wutschel** [comment]
Significant progress is seen in a [Kodi test build](https://forum.kodi.tv/showthread.php?tid=364983&pid=3078926#pid3078926). `"Playlist.Add"`, `"Playlist.Insert"` and the increase of `"playcount"` is working with this build.

To be able to show a proper thumbnail it is still preferred to receive `"thumbnail"` or `"type"` reflecting the playback of a recording as response to a `"Player.GetItem"` request. In worst case I can also make use of `"file"` (which starts with `"pvr:"` in such case) and use this as trigger to fall back to "icon" as thumbnail. This would result in showing the station logo on the NowPlaying screen.
