### ISSUE TITLE
Distribute offline

### ISSUE THREAD

**Issue by rzr** [xbmc/Official-Kodi-Remote-iOS#450]
Hi,
Is there a way to install without connecting to any store ?

**Comment by kambala-decapitator** [comment]
you can either download from Testflight or compile from source

**Comment by rzr** [comment]
well I have a not way to build  it (would a VM support a build process) so a deb file would be welcome for cydia

**Comment by kambala-decapitator** [comment]
yes, you can build in a VM.

we don't have plans to distribute to Cydia, but you could maintain that since it covers your use case (which looks quite rare).

**Comment by kambala-decapitator** [comment]
we can potentially attach an ipa stripped of code signature to a github release, but you'll have to repack it to deb on your own. Would that work for you?

**Comment by rzr** [comment]
yes this would not hurt , i can try and confirm, and maybe ipa would be able to be installed using some jb tools without deb re-packaging

**Comment by kambala-decapitator** [comment]
please try with this: [Kodi Remote.app.zip](https://github.com/xbmc/Official-Kodi-Remote-iOS/files/7520171/Kodi.Remote.app.zip)

it's just a zip of raw .app. If you'd require proper ipa structure, move the .app in `Payload` directory and zip it.

**Comment by rzr** [comment]
Yes this package is helpful , I managed to install it , but it fails to start on iOS 9.3.5

**Comment by kambala-decapitator** [comment]
sorry, I don't know how to help you: the latest TF version works fine on my iPod 5

**Comment by rzr** [comment]
ipad2 here I'll keep trying on next release

**Comment by kambala-decapitator** [comment]
launches just fine on my iPad 2 as well

**Comment by kambala-decapitator** [comment]
@sy6sy2 maybe you could give a hint?

**Comment by sy6sy2** [comment]
@rzr, From the app file given by Kambala you should be able to build a correct IPA file.
Then, on your jailbroken device you can install the IPA file with Filza.
If it crash on startup then you need to install AppSync Unified from Cydia (take care of using the official source, click this link from your jailbroken device : cydia://url/https://cydia.saurik.com/api/share#?source=https://cydia.akemi.ai/ )

If you still have a problem, I will try to reproduce on my device.

**Comment by kambala-decapitator** [comment]
@rzr from now on ipa is attached to every prelease, I guess the issue can be closed?

**Comment by rzr** [comment]
yes may this be double checked by @tarnyko too

**Comment by kambala-decapitator** [comment]
@rzr any extra input?

**Comment by rzr** [comment]
I can see the Ipa file at https://github.com/xbmc/Official-Kodi-Remote-iOS/releases/tag/1.10-b4
but for some reason I can't jb my ipad anymore, I'll give a try later

Btw deb package would be welcome too along it's apt source.

**Comment by kambala-decapitator** [comment]
> Btw deb package would be welcome too along it's apt source.

I have no experience with this, a PR is welcome
