### ISSUE TITLE
TF crash in channel guide

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#453]
all from same user.

> selected channel guide while in tv group, reproduceable

> Channel guide not working when in group view mode

[CueQgBnMOxYZeYoRDMvmsr.xccrashpoint.zip](https://github.com/xbmc/Official-Kodi-Remote-iOS/files/7475770/CueQgBnMOxYZeYoRDMvmsr.xccrashpoint.zip)

**Comment by wutschel** [comment]
Confirmed, looking into it.

**Comment by wutschel** [comment]
Fixed. This was a nice one.
