### ISSUE TITLE
1.8.1 crashes

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#465]
[Points.zip](https://github.com/xbmc/Official-Kodi-Remote-iOS/files/7511347/Points.zip)

**Comment by wutschel** [comment]
Three resets:
1. "VM - Fault hit memory shortage". Not sure what to do about it.
2. Crash in `canEditRowAtIndexPath` when checking if a row is editable. Added an out-of-bounds check. When out-of-bounds responds with NO (= not editable).
3. Code which could cause the out-of-bounds access in `changeViewMode` already got removed.
