### ISSUE TITLE
Support search in grid/wall mode

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#467]
Continuing #414

**Comment by wutschel** [comment]
I reached 80% functionality for this by now. The last 20% will now take a while.

What works (tested with albums, artists and movies):
- Search field usable
- Correct results are shown
- Longpressing or selecting an item processes the details of the correct item

What does not work yet:
- No section header showing the amount of results
- In some use cases the search bar is not shown, but when clicking the empty area the search works

Screenshots:
https://abload.de/img/simulatorscreenshot-ivbkf8.png
https://abload.de/img/simulatorscreenshot-ijvk5q.png
https://abload.de/img/simulatorscreenshot-i42kwb.png
https://abload.de/img/simulatorscreenshot-iz9kwn.png

**Comment by wutschel** [comment]
Now with section header showing the amount of items after search: 
https://abload.de/img/simulatorscreenshot-iqdkqt.png

The issue with the non-showing search bar is more complicated. In [this screenshot](https://abload.de/img/simulatorscreenshot-ipckym.png) the search bar's background was colored in green. So it **is** shown, but without content. When you click the bar, the search fields becomes active and shows the content. I searched the web for similar problems (`UICollectionView` with disappearing search bar) and found a few hits.  None of them helped so far, and one was pointing to a solution which was valid for iOS7 and is also used in the Remote App's code. It has no effect, I will remove it.

@kambala-decapitator, any idea where to look at?

**Comment by wutschel** [comment]
I found a solution for this: Creating a new instance of `UISearchController` when toggling between `UITableView` (list view) and `UICollectionView` (grid view) resolves the graphical issue. I will create a draft PR for this later today. This needs more testing and verification.
