### ISSUE TITLE
TF feedback: app mode not preserving

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#477]
Pour les vidéos lors l’édition de la liste lecture, à chaque changement l’application retourne sur le mode musique; cela est très embêtant si l’on veut organiser l’ordre de diffusion ou la suppression de plusieurs épisodes

For videos when editing the playlist, each time the application changes, the application returns to music mode; this is very annoying if you want to organize the broadcast order or the deletion of several episodes

**Comment by wutschel** [comment]
Confirmed.

**Comment by wutschel** [comment]
I took a deeper look into this and only recognize this problem for iPhones. The logic does the following:
1. When re-entering NowPlaying and if playback is going on
-> Show the playlist which is playing.
2. When re-entering NowPlaying and if nothing is playing 
-> Show Music playlist as a default.
3. When not leaving NowPlaying but switching between NowPlaying and Playlist view 
-> Preserve whatever was selected before.
4. For iPad: Playlist follows the playing playlist. If nothing is playing, the Music playlist is selected.

I understand that for users there is an inconsistency between re-entering NowPlaying (from any other menu), or switching between NowPlaying and Playlist view. There is only one clean option to change this: Let last user action dominate App's lifecycle. 
1. If the App was started w/o user action, it will show the current playing playlist. If nothing is playing, it will fall back to "Music".
2. If the user manually selected "Video", this will always be shown when entering the playlist view again -- even though "Music" is playing.
2. If a user now starts playing music (from another menu or via the server) the playlist will follow this.
This is consistent to the use case where users switch between NowPlaying and Playlist view. It is also consistent to the behaviour on iPad.

**Comment by wutschel** [comment]
While working on something else (handling of pictures playlist) I think I now really understood the complaint. The App in its current version (1.9) does simply falls back to Music playlist after any editing step of a Movie playlist. This is really annoying. I will fix this as part of the bigger rework I am currently on.
