### ISSUE TITLE
AppStore feedback: sorting movies

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#493]
Hallo liebe Entwickler, die neue Version ist ganz nah dran. Könnt ihr bitte bei der Filmübersicht nach Filmgenre die Möglichkeit der Sortierung nach Jahr, Bewertung, Name usw. hinzufügen? Dann ist die neue Version perfekt.

Hello dear developers, the new version is very close. Could you please add the option of sorting by year, rating, name, etc. to the film overview by film genre? Then the new version is perfect.

**Comment by wutschel** [comment]
This should be fixed with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/417 and already testable in the TF build. Can you contact the user and point to the TF build?

**Comment by kambala-decapitator** [comment]
responded to the user
