### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#496]
I think next release can be called 1.9 actually.

Assigned milestone to a few currently opened PRs, I don't think we should add anything else for this release.

**Comment by wutschel** [comment]
Thanks and fully agree. Let us now focus on fixing issues reported from TF and get more test depth. I will prepare the release notes. And it seems I need to provide some updated screenshots again :)

**Comment by kambala-decapitator** [comment]
New SSs aren't strictly necessary I believe as long as UI changes aren't huge. Not insisting on the either way.

I'll raise app version right before sending to review that we don't have to wait for TF approval.

**Comment by wutschel** [comment]
The UI now has a different main menu (Radio/Live TV/Videos) and the new upper right buttons (Now Playing and Remote) in each menu. It will be good to update at least the screenshots related to these screens.
