### ISSUE TITLE
Radio/Recording thumbnail backgrounds in wall view

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#500]
In the current build 2905 the background color of thumbnails in wall view is not correct.

Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2021-11kmksk.png"><img src="https://abload.de/img/bildschirmfoto2021-11kmksk.png" /></a>

**Comment by kambala-decapitator** [comment]
I don't see what's wrong =)

**Comment by wutschel** [comment]
Should look like this (no white frames):

<a href="https://abload.de/image.php?img=bildschirmfoto2021-11j3ja1.png"><img src="https://abload.de/img/bildschirmfoto2021-11j3ja1.png" /></a>
