### ISSUE TITLE
Now playing overlay: ‚repeat‘ and ‚shuffle‘ buttons no longer work

### ISSUE THREAD

**Issue by howie-f** [xbmc/Official-Kodi-Remote-iOS#506]
…on an iPadAir2. the two buttons are not _touchable_ anymore, instead the overlay just closes. funny thing, on my old - still in use iphone5 - it works as expected.

v1.9 (2914) but the problem already existed with the previous version. i noticed it yesterday

**Comment by wutschel** [comment]
Thanks for finding this right on time. It was broken since 1.8.2-b2 (October 22nd). Just fixed it.
