### ISSUE TITLE
Enhancement - "Play Using" Context Menu Option for UPNP client playback.

### ISSUE THREAD

**Issue by sbuser** [xbmc/Official-Kodi-Remote-iOS#51]
I have multiple XBMC instances and generally find controlling them with your app to be a great experience. It would become a fantastic experience if I could use the upnp options which work from the applications on the ios app.

If I'm controlling XBMC from a computer I can simply get a context menu and play back to any of my XBMC devices seamlessly. I don't have to keep multiple libraries, update them all, etc. I just use one central device and play to the devices I'm interested in.

This should be a simple as adding an option to the context menu in the ios app that one currently gets to play the file - just add a play-to for each upnp client.

Thanks!

**Comment by wutschel** [comment]
The Kodi API still does not support this. 

@kambala-decapitator: Do you agree to close this?

**Comment by wutschel** [comment]
Happy 10th anniversary! ...with a nice gift.
