### ISSUE TITLE
json error when fetching program guide for a channel

### ISSUE THREAD

**Issue by howie-f** [xbmc/Official-Kodi-Remote-iOS#537]
merry x-mas 🌲

this happens on v1.10 (2939) ipad air
```
XBMC JSON-RPC Error: Invalid params.
(Code: -32602)
Data: {
    method = "PVR.GetBroadcasts";
    stack =     {
        message = "Missing parameter";
        name = channelid;
        type = integer;
    };
}

METHOD
PVR.GetBroadcasts

PARAMETERS
{channelnumber=1;properties=(title,starttime,endtime,
plot,plotoutline,progresspercentage,isactive,hastimer);}

```

v1.9 (2918) on the ancient iphone5 is fine -> refusing to update 🙂

**Comment by wutschel** [comment]
Hmm, I cannot test this in the next days. What Kodi server version do you use?

**Comment by howie-f** [comment]
yes, just checked it happens with leia, matrix, nexus. don‘t worry, you can always fallback to the gui

**Comment by wutschel** [comment]
Fixed it. The configuration for the menu is pretty complicated. I fell into a similar trap already, but obviously did not check my changes well enough. Anyway, works now -- to my best knowledge. :)

**Comment by howie-f** [comment]
yay, great 🎉
