### ISSUE TITLE
WOL from IPAD IOS 8.0 not working

### ISSUE THREAD

**Issue by markh54** [xbmc/Official-Kodi-Remote-iOS#54]
G'day There,

Firstly - i truly love this APP. Ive only found one tiny issue with it.

I have a ION based HTPC running Openelec 4.2.0 (XBMC Gotham 13.2).  And is set to use WOL.
From my Android running Yatze app - I can boot up the machine no problems using WOL.

However, i simply get no response when i try it from this app.
Is there a log file or something i can check to see what command is trying to be sent to my HTPC ?

ps. My HTPC has a Static IP and connected via LAN cable to my modem.

**Comment by joethefox** [comment]
Hi and thank you!

I'm using a pure C snippet to do a WOL. The code is here https://github.com/joethefox/Unofficial-Official-XBMC-Remote/blob/master/XBMC%20Remote/AppDelegate.m#L3033-L3082

and it seems working fine here. Have you double checked if the mac address filled into the app is the correct one?

**Comment by Klaus1189** [comment]
For me The app is working, but WOL doesn't work anymore sonce I updated my iPad Air 2 to iOS 9.3.
I reinstalled the app, but it doesn't change anything. Every other feature is working for me. Strange. Please help me.

**Comment by joethefox** [comment]
fixed with https://github.com/xbmc/Official-Kodi-Remote-iOS/commit/a58e8b06f286e2a24d87a5476ae022ff824c8af6
