### ISSUE TITLE
App Store feedback: view options for TV shows and UI of Kodi servers

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#544]
Does what it needs to. Would be good to have the same view options for TV shows as there are for movies. And the way you organise and connect to different instances of Kodi could be less convoluted. Overall it’s ok, it’s free so can’t complain too much.

**Comment by wutschel** [comment]
Was this feedback from an iPad or an iPhone user?

**Comment by kambala-decapitator** [comment]
such info isn't displayed. 

should I try inviting the user to this issue?

**Comment by wutschel** [comment]
> should I try inviting the user to this issue?

Yes, will be good to hear directly what the user has in mind.
