### ISSUE TITLE
App Store feedback: Ugly interface

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#545]
The user interface layout looks way better but the buttons and color are pretty ugly. I wish Apple would implement a way to rollback apps to the previous version. This happens too many times.

**Comment by howie-f** [comment]
just want to add my 2 cents.
the buttons/icons are new, so once you're used to it, nice, no need to change.
i tried, but i can't make friends with the automatic color calculation for tv shows / backgrounds / text etc.
![IMG_0349](https://user-images.githubusercontent.com/58829855/148378913-48045392-0915-45cf-8a79-0acc1554c94a.jpg)

it's still hard imo, so my suggestion is:
pick a nice gradient of your choice (maybe season 2 in the picture is ok),
pick fixed color black for the text and use those for any season of any tvshow.

the auto calculation of the background is a cool feature and nice implemented, but every time i open that view i'm thinking "is that a bug?" :) (no offense)

**Comment by wutschel** [comment]
@kambala-decapitator, with out knowing which colors the user complains about this will be difficult to understand. You think it will be possible to get some more infos a d examples?

@howie-f, thanks for sharing this example

I personally still love the cover based coloring of backgrounds, texts and such. :)

What I can think of is to add an App setting to just use pre-defined gray scales instead of automatic coloring. There is a centralized method (`averageColor:inverse:`) which calculates the average color for all these use cases. It will not be rocket science to do this.

**Comment by kambala-decapitator** [comment]
asked the user to provide more info in this issue

**Comment by kambala-decapitator** [comment]
user edited the feedback:

> The user interface layout looks way better but the buttons and color are pretty ugly, some light gradients was way better. The other thing is that now you can put the remote position top or bottom but after several years like 3-5 my brain had memorized the location and did not have to look at night. So I wish I could setup at tje center like it was before. I wish Apple would implement a way to rollback apps to the previous version. This happens too many times.

**Comment by wutschel** [comment]
> user edited the feedback:

Thanks. This reads like the complain is solely on the remote screen itself. The remote screen's 3D-like look with gradients was replaced with a near-black 2D look of the buttons. To allow adding the volume bar to the remote screen the layout was changed and the buttons moved (see the screenshots below). Personally I still see this as an improvement, and the feedback especially on having the volume bar on the same screen is quite positive. It is the price of (another) improvement.

Screenshots:
<a href="https://abload.de/image.php?img=bildschirmfoto2022-0146ktl.png"><img src="https://abload.de/img/bildschirmfoto2022-0146ktl.png" /></a>

**Comment by wutschel** [comment]
@howie-f, I found time to do a quick implementation of the setting to disable automatic colorization of UI elements. Result (few examples only, left/right = LightMode/DarkMode) looks like this:

<a href="https://abload.de/image.php?img=bildschirmfoto2022-03cbjlv.png"><img src="https://abload.de/img/bildschirmfoto2022-03cbjlv.png" /></a>

**Comment by howie-f** [comment]
cool, this looks very smooth in my opinion. thanks @wutschel 🍻

**Comment by wutschel** [comment]
I agree, for non-colorized this looks really good. I can imagine not only you will prefer this. :)
Also I like the very simple solution which right from the start supports Light/Dark mode. 

PS: This motivates me to look into darkening the colorized UI when in DarkMode.
