### ISSUE TITLE
Maintenance: Coding Style changes from PR reviews

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#589]
When reviewing https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/526 several coding style changes were requested. 

In pattern `if (((NSNull*)bla != [NSNull null])) { ...` the cast should be removed, if `bla` is of type `id`.

Instead of `for (int i = 0; i < total; i++) {` use `for (x in y) {`

**Comment by wutschel** [comment]
Use `boolForKey` instead `[[userDefaults objectForKey:myKey] boolValue];`

**Comment by kambala-decapitator** [comment]
and `integerForKey`
