### ISSUE TITLE
TF crash from the latest test build

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#590]
[testflight_feedback.zip](https://github.com/xbmc/Official-Kodi-Remote-iOS/files/8014756/testflight_feedback.zip)

**Comment by wutschel** [comment]
From the code I can only see a possible out-of-bounds access (which would have been solved with bddc6549). I am not sure, if the crash log is matching this. Can you tell?

**Comment by kambala-decapitator** [comment]
not quite sure that commit would solve the crash as it happens right on app resume.

Next function in stacktrace is related to mutable dictionary. Is `mainParameters` an array of dictionaries?

**Comment by wutschel** [comment]
> Next function in stacktrace is related to mutable dictionary. Is `mainParameters` an array of dictionaries?

`mainParameters` is a mutable array of multiple types, including dictionaries, strings, numbers and arrays.

**Comment by wutschel** [comment]
The same log is contained in https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/604. Let us close this one.
