### ISSUE TITLE
Maintenance: Migrate to block-based animation

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#599]
The App's code uses both the non block-based and the preferred block-based animation. It is desired to completely migrate to block-based, from iOS13 on the non block-based is deprecated.

**Comment by wutschel** [comment]
@kambala-decapitator, locally I could already work on this and the migration is nearly finished. The animations still look as before (was even finding an animation bug in NowPlaying). But there is one animation methods where I could not figure out how to do this block-based.

`[UIView setAnimationTransition: UIViewAnimationTransitionFlipFromLeft forView:myView cache:YES];`

Works:
```
[UIView animateWithDuration:0.2
                      delay:0.0
                    options:UIViewAnimationOptionCurveEaseIn
                 animations:^{
    transitionView.alpha = 0.0; 
    [UIView setAnimationTransition:UIViewAnimationTransitionFlipFromLeft forView:transitionView cache:YES];
}
```

Does not work:
```
[UIView animateWithDuration:0.2
                      delay:0.0
                    options:UIViewAnimationOptionCurveEaseIn | UIViewAnimationOptionTransitionFlipFromLeft
                 animations:^{
    transitionView.alpha = 0.0;
}
```

**Comment by kambala-decapitator** [comment]
`[UIView transitionWithView:...]`

it's so easy to discover in the documentation ;)

**Comment by wutschel** [comment]
Ouch. Funnily enough I was on that page, but was not recognizing `animateWithDuration:duration ...` is different to `transitionWithView:duration...`. Sorry for bothering you, I migrated the code now.
