### ISSUE TITLE
Feature: Wake-On-LAN automatically called at start

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#602]
Suggested by a user in [this forum post](https://forum.kodi.tv/showthread.php?tid=367075&pid=3087077#pid3087077). Add an App setting which lets the App send Wake-On-LAN at startup automatically.

**Comment by kambala-decapitator** [comment]
by default it should be disabled

**Comment by wutschel** [comment]
Is it ok to call WOL each few seconds until the connection is established? The function checkServer is called each 3 seconds, it would be quite simple to hook up WOL there. I could of course also add some logic to only call this once and never again.

**Comment by kambala-decapitator** [comment]
to my understanding you need to send WoL only once and start connection attempts after that

**Comment by StSaens** [comment]
I don’t think there’s a downside to sending a WOL more than once. So if this is easiest then that’s best.

Thanks!
