### ISSUE TITLE
Showstopper: Remote does not dismiss on iPad with iOS 11

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#606]
Either this is something which worked before rebase/merge with other changes, or I have complete overseen this. The new remote popover does simply not dismiss on iOS 11.x when touching the are outside of the remote.

**Comment by wutschel** [comment]
Also other popovers (e.g. `ShowInfoView` when clicking an item in iPad fullscreen) are not dismissed in the App running on iOS 11. For each of those the "Done" or "X" buttons were added.

**Comment by kambala-decapitator** [comment]
I think that's how it used to work by default. Maybe popover controller has some dedicated property to control the behavior?

**Comment by wutschel** [comment]
I was thinking of adding a "Done" or "X" button to close the popover. That's how this works for the other popover as well.

**Comment by kambala-decapitator** [comment]
btw just understood that I confused popover with page sheet mentioned in the other new issue :) popover has always been dismissed by tapping outside iirc.

are we talking about the deprecated UIPopoverController?

**Comment by wutschel** [comment]
Oh sorry, I meant the type `UIModalPresentationFormSheet`.

**Comment by kambala-decapitator** [comment]
then I think this is valid:

> I think that's how it used to work by default

**Comment by wutschel** [comment]
Is it possible to enable this feature (dismiss when clicking into outside area)? There are a few more form sheets which can cause trouble.

**Comment by kambala-decapitator** [comment]
> Is it possible to enable this feature (dismiss when clicking into outside area)?

I don't recall such functionality out of the box on older iOS

**Comment by wutschel** [comment]
Ok. I found different ways of addressing the topic: the iPad's remote now has close button, and the other problematic screens cannot be reached for old iOS versions when in fullscreen.
