### ISSUE TITLE
Unrecognized Locale os-os

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#613]
Output on uploading to AppStoreConnect:

WARNING ITMS-90176: Unrecognized Locale - The locale names used in localization directories at ( "Payload/Kodi Remote.app/Settings.bundle/os-os.lproj" ) are invalid. iTunes supports BCP47 but not the UN M.49 specification. Refer to the Language and Locale Designations guide at https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html for more information on naming your language-specific directories.

**Comment by kambala-decapitator** [comment]
@gade01 pinging you in case you haven't received notification that you're an assignee

**Comment by gade01** [comment]
@kambala-decapitator Thanks for the heads up.
I think we should just remove that language.
It currently has only 1 not very active translator.

Should I do a PR?

**Comment by kambala-decapitator** [comment]
yes please, I fully agree

**Comment by gade01** [comment]
I actually just realised that we have _no_ translators for that language at all.
The translations we have now come from Transifex.

The PR is here: https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/615

Do you see more unsupported languages?

**Comment by kambala-decapitator** [comment]
this was the only one reported in the warning, I guess all others are supported.

**Comment by gade01** [comment]
Sounds great, thanks.
