### ISSUE TITLE
Size of modal remote sheet on iPads

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#620]
We already got feedback from 1 user that the remote became too small (especially compared to the supersized remote before) on iPad with the change to use `UIModalPresentationFormSheet`. The size currently is chosen match half the iPad's screen width in portrait mode.

Screenshots:
https://abload.de/img/04-simulatorscreenshocfjek.png (before)
https://abload.de/img/04-simulatorscreenshoryjip.png (new)

It is possible to extend the size further to stay within the screen in iPad's landscape mode (either overlapping the bottom toolbar or not overlapping).

Non-Overlapping (+18% stretched):
https://abload.de/img/simulatorscreenshot-iq9jrk.png (landscape)
https://abload.de/img/simulatorscreenshot-iurkcc.png (portrait)

Overlapping (+30% stretched):
https://abload.de/img/simulatorscreenshot-i1tj0u.png (landscape)
https://abload.de/img/simulatorscreenshot-irwjiz.png (portrait)

Personally, I find the biggest version the worst and still like the smallest version. But I have no iPad I cannot really judge how the usability is with the current size of the TestFlight 1.10 builds.

**Comment by wutschel** [comment]
@kambala-decapitator, this is the only thing which bothers me a bit. Size can be increased, but we really have few feedback.

**Comment by heitbaum** [comment]
I like the new size and behavior - aligns with the iPhone flexibility - which I find good as a remote.

![A3D8A1F6-33D3-4A18-A75A-48DE5E89D8A5](https://user-images.githubusercontent.com/6086324/159147158-df48b3c4-3abd-4897-940b-ebc7fb58ebc9.png)

**Comment by kambala-decapitator** [comment]
made short check - seems fine to me

**Comment by wutschel** [comment]
Thanks, guys. Then let's wait for the user community feedback.

**Comment by wutschel** [comment]
No negative feedback at all, I am closing this.
