### ISSUE TITLE
(3255) cannot set or delete pvr timer from program guide

### ISSUE THREAD

**Issue by howie-f** [xbmc/Official-Kodi-Remote-iOS#629]
happens on iPad Air 2… iPhone5 with version 3255 works.

iPad OS 15.3.1

![126F2C4E-C78B-4A72-B007-A430E2EAD11E](https://user-images.githubusercontent.com/58829855/158368647-487ac22d-a967-4f44-ae2e-4814813dd114.png)

**Comment by wutschel** [comment]
That was another bad one. Sorry for this.

**Comment by howie-f** [comment]
thanks for fixing :)

**Comment by wutschel** [comment]
> thanks for fixing :)

Can you confirm it is working again for you?

**Comment by howie-f** [comment]
yes @wutschel, working again. well done, thank you
