### ISSUE TITLE
unfinished localisations in the settings bundle

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#632]
@wutschel I remember we discussed this in some PR. How would you like to proceed for the release? Maintain a list of localisations to exclude or include anything there is?

@gade01 mentioning you in case you also have some thoughts on this.

**Comment by wutschel** [comment]
I remember @gade01 proposed to only include translations when they reached 50%.

**Comment by gade01** [comment]
@kambala-decapitator @wutschel 
It's totally up to you, but I think it would make sense.
Maybe around 30-40% as there is a lot of strings.

You can see the status here:
https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-main/
https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-settings/
https://kodi.weblate.cloud/projects/kodi-remotes/official-ios-remote-infoplist/

**Comment by kambala-decapitator** [comment]
I guess it's better to use Weblate API to find out which languages meet the threshold we set then

**Comment by kambala-decapitator** [comment]
personally I'd simply include all languages since it's only about settings, I doubt a lot of people go there

**Comment by wutschel** [comment]
In my opinion we should only add the settings translations when we add the main translations at the same time. Otherwise the user might not easily recognize what is configurable (e.g. enabling "Pictures" for the main menu), if it is later not translated the same in the App itself.

**Comment by kambala-decapitator** [comment]
> In my opinion we should only add the settings translations when we add the main translations at the same time. Otherwise the user might not easily recognize what is configurable (e.g. enabling "Pictures" for the main menu), if it is later not translated the same in the App itself.

I'm fine with this. Would be even easier to script - no need for weblate api.

I'd still exclude non-ready languages only when making the build that will be submitted for appstore review.

**Comment by wutschel** [comment]
You propose to add all languages for TF builds, and only reduce to the ones with reasonable coverage for releases? Sounds quite nice. This might even help motivate translators and helps them seeing the context.

**Comment by kambala-decapitator** [comment]
> You propose to add all languages for TF builds, and only reduce to the ones with reasonable coverage for releases?

yes, that's my intention

**Comment by wutschel** [comment]
Looks like with the last updates Finnish (fi_fi) and Korean (ko_kr) reach nearly 100%. They could be added. Will this be done you script? Should I add this to the Release Notes then?

**Comment by kambala-decapitator** [comment]
those localisations must be included in the project first, I mean the Localizable.strings and InfoPlist.strings files.

this issue is only about settings bundle that is added as a directory reference in the project, hence requires files to be moved/deleted from the directory that they don't get into the app bundle.

**Comment by wutschel** [comment]
> those localisations must be included in the project first, I mean the Localizable.strings and InfoPlist.strings files.

Added them with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/638, but https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/637 should be merged first to update fi_fi to the desired state.
