### ISSUE TITLE
Issues in strings to translate

### ISSUE THREAD

**Issue by pedro-mendonca** [xbmc/Official-Kodi-Remote-iOS#65]
Hi @joethefox 

As I'm translating this to pt_PT I've found some minor issues I'd like to report.
on https://github.com/joethefox/Unofficial-Official-XBMC-Remote/blob/iOS7/XBMC%20Remote/en.lproj/Localizable.strings#L171 there are two typos in "No sever mac address definied". This string is duplicated as there is another in https://github.com/joethefox/Unofficial-Official-XBMC-Remote/blob/iOS7/XBMC%20Remote/en.lproj/Localizable.strings#L120 "No server MAC address defined".
I didn't change this without reporting it first, as I think these strings were automattically parsed from the code and the error subsists somewhere else, probably here at https://github.com/joethefox/Unofficial-Official-XBMC-Remote/blob/151b35224e8a134c053aa552c74833b090cb7052/XBMC%20Remote/RightMenuViewController.m#L215, but as I'm not a developer I'm not sure if is enough to just edit this here.

Another typo I've found is a simple double space in https://github.com/joethefox/Unofficial-Official-XBMC-Remote/blob/iOS7/XBMC%20Remote/en.lproj/Localizable.strings#L241.
Again, I'm not changing this without your confirmation that is enough to just edit this out.

**Comment by joethefox** [comment]
Yep, what you have found are errors. The left part is the "key" used into the code. Leaves the errors there, I will fix them after merging your translation and I will remove the wrong "No sever mac address definied" and the double space in a separated commit for all the languages.

**Comment by pedro-mendonca** [comment]
Ok, so I'll maintain the typos in the keys, but with correct translations.
Still, do you want me to keep marking and informing you of more errors like these? It can be time consuming, I could just make a PR to correct them all.
Meanwhile... 
https://github.com/joethefox/Unofficial-Official-XBMC-Remote/blob/iOS7/XBMC%20Remote/en.lproj/Localizable.strings#L246 --> "version 13  or superior"
:)

**Comment by joethefox** [comment]
oh sure a separate PR to correct them all would be absolutely welcome, thank you. But in this case you need to search the wrong key also into the code to correct it.

**Comment by pedro-mendonca** [comment]
Ok, that's what I needed to know, if it's enough to also correct the key in the code.
I'll do it than.

**Comment by pedro-mendonca** [comment]
One more:
In https://github.com/joethefox/Unofficial-Official-XBMC-Remote/blob/iOS7/XBMC%20Remote/en.lproj/Localizable.strings#L127... `to clear the %@playlist?`
The `%@` is a playlist name? If so, maybe it's missing a space, like this `to clear the %@ playlist?`

**Comment by joethefox** [comment]
no, in this case It's wanted. I have done this little hack to support both language form "Music playlist" for anglophone and "playlist musicale" for italian for example. The vars are the  https://github.com/joethefox/Unofficial-Official-XBMC-Remote/blob/iOS7/XBMC%20Remote/en.lproj/Localizable.strings#L111-L112

so in italian the translated string is swapped https://github.com/joethefox/Unofficial-Official-XBMC-Remote/blob/iOS7/XBMC%20Remote/it.lproj/Localizable.strings#L127
and the vars are
https://github.com/joethefox/Unofficial-Official-XBMC-Remote/blob/iOS7/XBMC%20Remote/it.lproj/Localizable.strings#L111-L112

hope I was clear :)

**Comment by pedro-mendonca** [comment]
Yes, I do understand that. In portuguese it's swapped like italian.
I just found odd that you missed the space between "playlist" and the var, I now see that the space is considered in the "music " and "video " strings. I think this might cause other translators many doubts, if I didn't ask you I wouldn't understood it and might even missed that small space. I now have to change the my "video " and "music " strings.
I suggest you include some commenting in the strings file on the right of theese 3 strings, just to help translators on it. I also think that the space should be included in the main sentence, and not in the two small strings, it's clearer to translators.

**Comment by pedro-mendonca** [comment]
Also, as "Music" and "Video" strings already exist, you could avoid redundancy of translation strings by just having `"Are you sure you want to clear the %@ playlist?"` and use the strings at https://github.com/joethefox/Unofficial-Official-XBMC-Remote/blob/iOS7/XBMC%20Remote/en.lproj/Localizable.strings#L16-L17

**Comment by joethefox** [comment]
absolutely right your two last comments. I don't recall at the moment but should be there some reason why I chose to do that (apart from that I could be drunk at that time, grant me the doubt :) )... I will revise that part to see if this ugliness can be  avoided.

About unifying the word "Music", my thought: in English we have the multipurpose word "music" that can be used alone or with "music playlist". In Italian, you have one different word for every meaning, so "Music" become "Musica" if alone but "music playlist" become "playlist musicale" and not "playlist musica" (even if correct, is less natural)

**Comment by pedro-mendonca** [comment]
The only problem I see here is that, in the italian example, it's "la playlist musicale" and not "la playlist Musica". The lack of context here becomes a problem.

**Comment by pedro-mendonca** [comment]
We just wrote the same, at the same time :D

**Comment by joethefox** [comment]
lol, yes :)

**Comment by pedro-mendonca** [comment]
I'm already seeing a problem in portuguese too, I can deal with that like "playlist de Música", but still it would be great to avoid the M, better like "playlist de música". In gettext I'm used to context in strings, does it exist here also?

**Comment by pedro-mendonca** [comment]
A fast solution would be to include "playlist" in the string:
`"Are you sure you want to clear the %@?"`
`"music playlist"`
`"video playlist"`

**Comment by joethefox** [comment]
yep, works. Seems that you have found the right way and you confirm my mental state at that time :)

**Comment by pedro-mendonca** [comment]
Next step might be hard, changing all language files might be odd, particularly in zh-Hans.lproj...

**Comment by joethefox** [comment]
if you want leave it as it is, I can take this task

**Comment by pedro-mendonca** [comment]
Ok than, I'll leave it tou you, sorry to bother you this much last few days :)

As I was already doing something on this, I just let you know something I found.
While I was making my first find+replace here, I found some keys that I'm not sure if they're wrong:
https://github.com/joethefox/Unofficial-Official-XBMC-Remote/blob/iOS7/XBMC%20Remote/NowPlaying.m#L2705
and
https://github.com/joethefox/Unofficial-Official-XBMC-Remote/blob/iOS7/XBMC%20Remote/NowPlaying.xib#L457

I believe the ones to change might be
https://github.com/joethefox/Unofficial-Official-XBMC-Remote/blob/iOS7/XBMC%20Remote/NowPlaying.m#L2050
and
https://github.com/joethefox/Unofficial-Official-XBMC-Remote/blob/iOS7/XBMC%20Remote/NowPlaying.m#L2053

**Comment by joethefox** [comment]
absolutely no trouble at all! I will check those keys

**Comment by pedro-mendonca** [comment]
I've completed the pt-PT strings. I've started generating the PNGs.
For now I've found that two fonts were missing in the repo, Helvetica and LafayetteComicPro, but I manage to install them.
I think that a button is missing, the black "Playing" one. Or is it in some layer? I'll check it later.

One doubt, should the app name in the info screen be translated?

**Comment by joethefox** [comment]
Ah the fonts, right. Helvetica should be copyrighted so can't be added to the repo. I will check the LafayetteComicPro ttf license. 

The black "playing" is for iOS < 7 so can be ignored now days. 

For the app name translation, as you like :)

**Comment by pedro-mendonca** [comment]
Ok, I understand.

**Comment by pedro-mendonca** [comment]
Portuguese is complete. Just pushed it.
I need to test some strings in context, I'm will now testing it in iOS9.02.
I've prepared pt-PT for your corrections of the playlist related strings, but of course I'll check it all again after you push your changes.
I did just the Help Menu for 2x, I'll do it later for ipad and maybe for low fi. Are all these needed?

**Comment by joethefox** [comment]
solved
