### ISSUE TITLE
1.10 crash reports

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#655]
[CVhThzqDjdc6Q2Gd7TzebB.xccrashpoint.zip](https://github.com/xbmc/Official-Kodi-Remote-iOS/files/8355157/CVhThzqDjdc6Q2Gd7TzebB.xccrashpoint.zip)

**Comment by wutschel** [comment]
Not sure how this can happen, but obviously the received data had the wrong format / wrong class. I added a check and an error message for these cases.

**Comment by wutschel** [comment]
> one more crash:

That was an interesting debugging journey which ended in a straight forward division-by-0 fix.
