### ISSUE TITLE
Translate to catalan

### ISSUE THREAD

**Issue by elboletaire** [xbmc/Official-Kodi-Remote-iOS#67]
I would like to translate the app to Catalan. How should I proceed?

**Comment by joethefox** [comment]
Nice, thank you! Let me the time to prepare the project to support also Catalan.

**Comment by elboletaire** [comment]
Perfect, thanks :smiley:

**Comment by joethefox** [comment]
Hi, I have added support for Catalan localization to the project.

Now you should translate this two files ("key" = "value"):
* https://github.com/joethefox/Unofficial-Official-XBMC-Remote/blob/iOS7/XBMC%20Remote/ca.lproj/Localizable.strings
* https://github.com/joethefox/Unofficial-Official-XBMC-Remote/blob/iOS7/XBMC%20Remote/Settings.bundle/ca.lproj/Root.strings

for any info or question you can refer to this forum thread -> http://forum.kodi.tv/showthread.php?tid=254016

**Comment by elboletaire** [comment]
Nice, I'll try to do it during this week :smile:

**Comment by joethefox** [comment]
closed due to inactivity

**Comment by elboletaire** [comment]
Wow, I've absolutely forgot about this :confused:. If you have not removed the catalan support I'll try to find a moment to translate it (am not gonna say 'during this week' after this).

**Comment by joethefox** [comment]
no problem at all! :) The catalan support was removed due to matters for publishing to app store. But no need to rush, I will re-create the catalan branch and I will ping you here to inform you (the translatable parts are explained here -> http://forum.kodi.tv/showthread.php?tid=254016 )

**Comment by elboletaire** [comment]
Thanks :smile:

**Comment by joethefox** [comment]
Hi, 

I've added the "Catalan_translation" branch ->https://github.com/xbmc/Official-Kodi-Remote-iOS/tree/Catalan_translation

Don't hesitate to contact me with any questions

**Comment by elboletaire** [comment]
Ok thank you again @joethefox! I'll be out during the weekend so I'll try next week 😃

**Comment by wutschel** [comment]
@fuzzard, can this be closed as the PR was merged?

**Comment by elboletaire** [comment]
Guess there's no reason to maintain it open indeed
