### ISSUE TITLE
UI Bug [iOS 10.3.4] [iPad] Remote Button & Next Button Overlap 

### ISSUE THREAD

**Issue by nikhilk0** [xbmc/Official-Kodi-Remote-iOS#680]
There's a UI bug present in the latest App store version, where the remote button and next button overlap on the bottom toolbar.
Present in both portrait and landscape mode.

Model - iPad 4
iOS Version - 10.3.4
App Version - 1.10.1

![IMG_0032](https://user-images.githubusercontent.com/45728234/173216561-bad23295-c736-4221-8227-6c3e41396b94.PNG)

**Comment by kambala-decapitator** [comment]
Could you please check if the same issue is present in the testflight version?

**Comment by wutschel** [comment]
Could be similar to the effect seen in https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/391. As a kind of workaround for this problem we could avoid drawing the remote icon for older version. But I cannot test these older versions anymore.

**Comment by kambala-decapitator** [comment]
I'll check if it's reproducible on my iPad running 9.3

**Comment by wutschel** [comment]
Somehow I think this is related to auto layout. In the picture above the distance / free space between the icons is bigger than what I see using newer iOS versions.

**Comment by nikhilk0** [comment]
The issue is present in the testflight version.

**Comment by kambala-decapitator** [comment]
> I'll check if it's reproducible on my iPad running 9.3

same here as expected

**Comment by kambala-decapitator** [comment]
> Could be similar to the effect seen in #391.

yes, I guess that's it.

the following tweak made the buttons look good on my iPad:

```diff
diff --git a/XBMC Remote/NowPlaying.m b/XBMC Remote/NowPlaying.m
index e49f836c..3300a98b 100644
--- a/XBMC Remote/NowPlaying.m	
+++ b/XBMC Remote/NowPlaying.m	
@@ -2333,12 +2333,21 @@ - (void)setIpadInterface {
     NSMutableArray *items = [NSMutableArray arrayWithArray:playlistToolbar.items];
     [items removeObjectAtIndex:14];
     [items removeObjectAtIndex:13];
+    [items removeObjectAtIndex:12];
     [items removeObjectAtIndex:10];
     [items removeObjectAtIndex:8];
     [items removeObjectAtIndex:6];
     [items removeObjectAtIndex:4];
     [items removeObjectAtIndex:2];
     [items removeObjectAtIndex:0];
+    __auto_type createFixedSpace = ^{
+        UIBarButtonItem *b = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemFixedSpace target:nil action:NULL];
+        b.width = -7;
+        return b;
+    };
+    for (NSInteger i = items.count - 1; i >= 0; --i) {
+        [items insertObject:createFixedSpace() atIndex:i];
+    }
     [playlistToolbar setItems:items animated:NO];
     playlistToolbar.alpha = 1.0;
     
```

@wutschel  you'd also need to add a condition like "device is iPad and OS is < 1x" and adjust the comment a few lines above. The magic `-7` value has been determined by trial and error.

![Screen Shot 2022-06-16 at 14 14 45](https://user-images.githubusercontent.com/1557784/174059517-a25729b3-3d51-4050-ab97-6c3c6f42490f.png)

**Comment by wutschel** [comment]
Is this an error of auto layout? You mainly replace a flex width with fix width of dedicated width.

**Comment by kambala-decapitator** [comment]
toolbar items are laid out by iOS internally, one doesn't use auto layout there. Seems it's just a difference in iOS internals.

**Comment by wutschel** [comment]
Ok. I will look into refactoring this a bit, the code was written as hack when I started with obj c. I should be able to write a simple loop to remove all flex spaces and then add the last flex or fix space in a condition.

**Comment by wutschel** [comment]
Reworked: https://github.com/xbmc/Official-Kodi-Remote-iOS/commit/1317eecd7bc294faf3407e7fe89f9a337b38846d
Does this work for you on your device?

**Comment by kambala-decapitator** [comment]
> Reworked: [1317eec](https://github.com/xbmc/Official-Kodi-Remote-iOS/commit/1317eecd7bc294faf3407e7fe89f9a337b38846d)
> Does this work for you on your device?

I don't see any visual change, the issue is still there.

In your code you add fixed space only in the end, while in my code it's added after each item (except after the last one, it's not needed from my tests).

**Comment by wutschel** [comment]
> In your code you add fixed space only in the end, while in my code it's added after each item (except after the last one, it's not needed from my tests). Also not sure why you chose `-1` over `-7`.

It is because when I am also applying the "special treatment" for current iOS, it behaves same whether I am using -7 or just -1. I cannot test 9.x form 10.x without your help. 
When reviewing the xib I found the Bar Button Items which hold the buttons have a defined width of 0. Do you still need the workaround, if these are properly set to 38 (which is the button's width)? I can quickly push this for you to test.

**Comment by kambala-decapitator** [comment]
Let's try that. If not, I'd rather apply a quick and dirty fix.

**Comment by wutschel** [comment]
> Let's try that. If not, I'd rather apply a quick and dirty fix.

Code is updated: https://github.com/wutschel/Official-Kodi-Remote-iOS/tree/toolbar_layout_ios10

Btw, the exact number for the fixed spaces is 2. I can also change toward calculating this fixed space and even use this for newer iOS version. Then we are hopefully less dependent on automatic layout.

**Comment by kambala-decapitator** [comment]
don't see any changes:

![Screen Shot 2022-06-16 at 23 18 40](https://user-images.githubusercontent.com/1557784/174158695-bdf3e045-c522-42c3-a331-a92bc7e2a54d.png)

I can suggest an alternative implementation approach:

1. strip all spaces from the toolbar in xib
2. in code add the spaces when needed: for iPhone - flexible spaces, for iPad with iOS < 11 - fixed spaces like I suggested above, for other iPads - only flex space on the right

Btw there's an easier way to detect space items in code: all of them have `target == nil` and `action == NULL`.

**Comment by wutschel** [comment]
Does this look better now?
Code is updated: https://github.com/wutschel/Official-Kodi-Remote-iOS/tree/toolbar_layout_ios10

**Comment by kambala-decapitator** [comment]
the code change seems good, will make runtime test next week

**Comment by wutschel** [comment]
> the code change seems good, will make runtime test next week

Ok, made the changes you proposed and will now raise a PR.
