### ISSUE TITLE
Avoid crash updateChannelListTableCell

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#682]
From a comment by @kambala-decapitator it is per documentation not allowed to call `reloadData` between `beginUpdates`/`endUpdate`. In the App's code this might happen when the worker thread which updates the information for the visible channels is concurring with the updates trigger from the main thread. Choices to fix this is either using `dispatch_sync` to serialize any such event, or simply using `reloadData`. The latter will not only update the visible entries of the channel list, but all of them. 

The `reloadData` solution (https://github.com/xbmc/Official-Kodi-Remote-iOS/compare/master...wutschel:fix_channelupdate):
- Very long channel lists (if a user should e.g. have all satellite stations in the list) will be processed, even though not visible.
- Is `reloadData` thread-safe?

The `dispatch_sync` solution would require each `reloadData` call inside `DetailViewController` to be encapsulated with `dispatch_sync`. In this case I would introduce helper methods for this.

**Comment by kambala-decapitator** [comment]
reloadData must be called only from the main thread

**Comment by wutschel** [comment]
I need to correct myself. The function which possibly concurs is called via a timer. Is a timer spawning a worker thread well?

**Comment by kambala-decapitator** [comment]
Timer callback is called on the thread which you schedule the timer on

**Comment by wutschel** [comment]
Thanks, then this is main thread.

**Comment by wutschel** [comment]
Do I still need to use `dispatch_sync` to avoid that `beginUpdates` / `endUpdates` is interrupted by `reloadData` when all calls come from the main thread?

**Comment by kambala-decapitator** [comment]
> Do I still need to use `dispatch_sync` to avoid that `beginUpdates` / `endUpdates` is interrupted by `reloadData` when all calls come from the main thread?

sorry, missed your question. If you attempt to execute

```objc
dispatch_sync(dispatch_get_main_queue(), ^{ ... });
```

on main thread, you'll get into deadlock.
