### ISSUE TITLE
Crash in [FBSSceneSnapshotRequestHandle performRequestForScene:]

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#684]
With 1.9, 1.10 and mostly 1.10.1 I see several crashes which -- as far as I understand -- point to an issue when iOS kills the App because it was moved to background but is still active.

```
Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: FRONTBOARD 2343432205 
<RBSTerminateContext| domain:10 code:0x8BADF00D explanation:scene-update watchdog transgression: application<it.joethefox.XBMC-Remote>:33891 exhausted real (wall clock) time allowance of 10.00 seconds
ProcessVisibility: Background
ProcessState: Running
WatchdogEvent: scene-update
WatchdogVisibility: Background
WatchdogCPUStatistics: (
"Elapsed total CPU time (seconds): 21.930 (user 21.930, system 0.000), 100% CPU",
"Elapsed application CPU time (seconds): 0.024, 0% CPU"
) reportType:CrashLog maxTerminationResistance:Interactive>
```

Is there a standard way to find out more details and resolve this?

**Comment by kambala-decapitator** [comment]
the only "standard" way is to check what's going on when app is suspended. Maybe some synchronous network request takes time? This can be tackled with `[UIApplication.sharedApplication beginBackgroundTask...]`.

**Comment by wutschel** [comment]
Thanks, adding a link for future use: [Proper use of beginBackgroundTaskWithExpirationHandler](https://stackoverflow.com/questions/10319643/proper-use-of-beginbackgroundtaskwithexpirationhandler)

**Comment by wutschel** [comment]
I searched the code for synchronous network access, and I do not see any such cases in use. There is an implementation in the `JBKenBurnsView` using  the synchronuous`NSData dataWithContentsOfURL:`, but this is unused. Only exception I see are calls of `NSStream`'s `hasBytesAvailable` and `read:maxLength:` when receiving a trigger to read notifications via TCP inside `stream:handleEvent:`. Could this cause such problem?

We anyway did not see any of these issue since last two years.
