### ISSUE TITLE
translations conflict?

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#694]
I've accidentally merged #643 before #693, could it have any consequences?

@gade01 could you check?

**Comment by wutschel** [comment]
Should not result in problems as different translation files were changed (1x settings, 1x main).

**Comment by gade01** [comment]
@wutschel @kambala-decapitator 
Everything looks perfect at Weblate. 

Thanks so much for looking into this and for remembering.
As you know, it's always best to merge Weblate PR's first.
But no harm is done at all. :)

I have just pushed latest changes from Weblate just to be safe.

**Comment by kambala-decapitator** [comment]
Great, thanks a lot!

**Comment by howie-f** [comment]
i see `colorize ui automatically` in the settings instead of german `UI automatisch färben` (or something)… no idea if this is related

thanks again @wutschel i‘m really happy about this option

**Comment by gade01** [comment]
@howie-f 
https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/695/files is not merged yet ;)

**Comment by howie-f** [comment]
ah ja, danke 🙂

**Comment by gade01** [comment]
Bitte schön :)
