### ISSUE TITLE
Catalan and Spanish (Mexico) translations

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#705]
With https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/704 both languages are fully translated now and can be included. 

@kambala-decapitator, do I need to do anything for this, or are you handling this via your release scripts?

**Comment by kambala-decapitator** [comment]
those languages need to be included in the Xcode project (Localizable.strings), no other action needed
