### ISSUE TITLE
Issues when building with Xcode 14 for iOS 16

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#716]
I now installed Xcode 14 in parallel to 13.4.1 to look for issues caused by the new SDK. There are again a few issues visible. 
Remark: Building with 13.4.1 and running on iOS16 simulator works as expected.

Found so far:
- Menu Toolbar layout behaviour changed, now causing the safe area to be transparent on iPhone
- NavBar title empty after first time entering a menu, e.g. Music.
- PNowPlaying Toolbar layout behaviour changed, now causing the safe area to be transparent on iPhone

Menu built with Xcode 13.4.1: https://abload.de/img/simulatorscreenshot-ihzcir.png
Menu built with Xcode 14.0: https://abload.de/img/simulatorscreenshot-il6f9q.png
NowPlaying built with Xcode 14.0: https://abload.de/img/simulatorscreenshot-ifse4q.png

**Comment by wutschel** [comment]
The toolbar issues can be solved via a different way of implementing it (transparent toolbar and gray background with alpha 0.95 underneath). I am still having some smaller detail issues with the layout, but this can be generally solved. Maybe I am combining this with an overhaul of the NowPlaying design.

But the empty `NavigationItem.title` is weird. The value is definitely set, also when entering a menu for the first time. But it is not shown. A workaround is to simply set `self.navigationItem.title = @"_";` in `viewDidLoad` once. It seems setting the title for the first time does not work as long as there was no _non-empty_ content set before. Using `@""` or `@" "` as first value does not work -- because there's nothing to render?

@kambala-decapitator, you have any idea where to look at wrt `NavigationItem.title`?

**Comment by kambala-decapitator** [comment]
I haven't used 16 SDK yet, can't say. In https://developer.apple.com/documentation/ios-ipados-release-notes/ios-16-release-notes I see new navigation behavior documented for SwiftUI, so I believe there should also be new properties in UIKit. Please check respective header and search for `16.0`, as unfortunately there're no 13->14 API changes at https://developer.apple.com/documentation/uikit?changes=latest_major&language=objc

> Remark: Building with 13.4.1 and running on iOS16 simulator works as expected.

that's what we see on devices as well :)

**Comment by wutschel** [comment]
> lease check respective header and search for `16.0`
Ok, will do.

> that's what we see on devices as well :)
True, but this also means we're better prepared this time. Last time I only had new Xcode and couldn't test the combination of old Xcode with new iOS locally anymore.

**Comment by wutschel** [comment]
> lease check respective header and search for `16.0`

Ok, will do.

> that's what we see on devices as well :)
 
True, but this also means we're better prepared this time. Last time I only had new Xcode and couldn't test the combination of old Xcode with new iOS locally anymore.

**Comment by wutschel** [comment]
The workaround for `NavigationItem.title` is not needed anymore with Xcode 14.2. It was obviously fixed.
