### ISSUE TITLE
Layout problems on iPhone 14 Pro

### ISSUE THREAD

**Issue by wutschel** [xbmc/Official-Kodi-Remote-iOS#720]
On the new iPhone 14 Pro there are layout problems. Some UI elements are not positioned correctly.

Examples:
https://abload.de/img/simulatorscreenshot-ihqigp.png (info label for supported versions)
https://abload.de/img/simulatorscreenshot-ieyc1j.png (error message)
https://abload.de/img/simulatorscreenshot-iy9fed.png (message)
https://abload.de/img/simulatorscreenshot-i6fdcq.png (server info overlaps with eye)

**Comment by wutschel** [comment]
Obviously I miss something in how the view frame itself is positioned on the screen, or on how I calculate offsets/insets. In some places I can now use `CGRectGetMaxY(self.navigationController.navigationBar.frame);` which on iPhone 14 Pro is 103, on iPhone Xs it is 88. This fixes the layout problem for some views.
But oi other places I just use `UIApplication.sharedApplication.statusBarFrame.size.height` as offset, which his equal for both 14 Pro and Xs. For these I currently could not figure out what is wrong.

**Comment by wutschel** [comment]
Compiling the App with Xcode 14 resolves the problems.

**Comment by kambala-decapitator** [comment]
seems not using autolayout and using manual layout improperly starts causing issues :)

I'd still suggest to release next version built with Xcode 13, after that we can switch to 14.

**Comment by wutschel** [comment]
> seems not using autolayout and using manual layout improperly starts causing issues :)

You're welcome to join reworking. ;)

> I'd still suggest to release next version built with Xcode 13, after that we can switch to 14.

Agreed, migrating now would require too much time for testing via TF.

**Comment by kambala-decapitator** [comment]
I guess this would be the last thing to adjust for the release?

**Comment by wutschel** [comment]
I would just accept the small issue and fix it with next release when migrating to Xcode 14. But I have another change I would like to add, see https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/721.
