### ISSUE TITLE
[REQUEST] Porting Official Kodi Remote (IOS) to Android

### ISSUE THREAD

**Issue by madmax2** [xbmc/Official-Kodi-Remote-iOS#722]
Can the developer/s of Official Kodi Remote (IOS) port this to Android?

https://apps.apple.com/au/app/official-k...d520480364](https://apps.apple.com/au/app/official-kodi-remote/id520480364)

I have used this Official Kodi Remote (IOS) and Kore, 
and sadly the Official Kodi Remote (IOS) is more feature rich (e.g. can add custom commands)
and UI design is also much better than Kore UI (e.g. the buttons are larger and easier to press on IOS remote)

**Comment by kambala-decapitator** [comment]
no, sorry, we're not android devs
