### ISSUE TITLE
[FEATURE REQUEST] button to shut down/hibernate/sleep always available

### ISSUE THREAD

**Issue by pierocol** [xbmc/Official-Kodi-Remote-iOS#814]
It would be very useful if the action to power off the computer one way or another were always one click away. Currently, for example, if one is listening to music and the "Now Playing" screen is displayed, 4(!) screen taps are needed before one can power off the computer. My guess is that most users would always use one of the available processes (power off, hibernate or suspend). The best in my opinion would be to allow the user to select the preferred process as a setting and then always display the power off button, on all the screens.
Thank you very much for your consideration

**Comment by wutschel** [comment]
Hi, thanks for you proposal. Obviously you're on iPhone/iPod -- on iPad the OnOff menu is already available from the bottom toolbar. The problem with iPhone is the lack of space to place further icons. I already use the Navigation bar for the remote and NowPlaying short cut icons. What can be done -- from a perspective of space, nothing tested so far -- is to add a shortcut to OnOff menu only to the Remote and the NowPlaying screens, there we still have place for 1 button left.

Impressions:
<a href="https://abload.de/image.php?img=bildschirmfoto2022-12dcdhh.png"><img src="https://abload.de/img/bildschirmfoto2022-12dcdhh.png" /></a>

**Comment by pierocol** [comment]
Thank you wutschel, Yes, I meant the iPhone. I do have an iPad and the idea came from it. Having a power off button for the Remote and Now Playing screens would be an excellent solution. i would improve the user experience remarkably in my opinion. Thank you very much for considering my suggestion

**Comment by wutschel** [comment]
I now picked this up again and decided to change the power function to use action sheets. This makes it easier to introduce the buttons to NowPlaying and remote, it also unifies the implementation with iPad. There is still some work to do as now the success/fail response comes as a popup. This should be changed back to the nice green/red message slider which moves in from top of the screen.

https://ibb.co/nkYs89L -> example: NowPlaying with power icon
https://ibb.co/D9jjj2c -> power action sheet

**Comment by kambala-decapitator** [comment]
What if we simply add the power button to the main menu on the left?

**Comment by wutschel** [comment]
> What if we simply add the power button to the main menu on the left?

You mean adding a navigation bar and putting it there as left most element? Or can you otherwise share a mockup image?

**Comment by kambala-decapitator** [comment]
I mean the menu in the left sidebar where we have Music, Movies, ..., Now Playing, Remote Control, Global Search

**Comment by wutschel** [comment]
I would like to avoid to place the power function as another entry in the main menu. If at all, I would like to find a way to place in at the same location as for the other menus: navigation bar's right side. But in main menu I cannot create navigation bar, and I am also not aiming to place a view there just to hold the power button.

**Comment by wutschel** [comment]
Can be closed with https://github.com/xbmc/Official-Kodi-Remote-iOS/pull/1009, forgot to add it there.
