### ISSUE TITLE
Missing buttons on 1.13

### ISSUE THREAD

**Issue by StyleHack** [xbmc/Official-Kodi-Remote-iOS#864]
![ABDBFBDA-B0CD-43EC-8F96-6BEB6E7D5DFB](https://user-images.githubusercontent.com/40440433/226177373-f3141b39-d923-4c0f-a6f2-1245cbb909be.jpeg)

The buttons have disappeared in version 1.13. This was tested on the YouTube app. Please add them back.

**Comment by wutschel** [comment]
Thanks for raising this issue. I was observing the same and already raised a PR with a fix. You will see this resolved with one of the next TF updates.
