### ISSUE TITLE
Feature request: support RunScript for favorites (e.g. Autostop)

### ISSUE THREAD

**Issue by mbologna** [xbmc/Official-Kodi-Remote-iOS#865]
I am currently using Autostop service as a sleep timer. 
To use it in a comfortable way, they suggest to add a favorite item structured like this:

```
<favourite name="Autostop Sleep Timer">RunScript("service.autostop")</favourite>
```

It works when using the Kodi app, but when the favorite is called with the iOS app, I get: `Cannot do that (type = 'script')` [[code]](https://github.com/xbmc/Official-Kodi-Remote-iOS/blob/f432fb19481402da0c060c507a57e3e37b0ba85e/XBMC%20Remote/DetailViewController.m#L1561-L1576)

Is there any plan to support favorite 'script' actions?

[Related Autostop issue](https://github.com/jbinkley60/service.autostop/issues/2)

**Comment by wutschel** [comment]
I was not even aware of the 'script' type. Can you help with with what JSON command would need to be sent in this case?

**Comment by mbologna** [comment]
> I was not even aware of the 'script' type. Can you help with with what JSON command would need to be sent in this case?

I can try. How do I retrieve the JSON command?

**Comment by wutschel** [comment]
@jbinkley60, can you maybe shed some light on this?

**Comment by wutschel** [comment]
Just like this? `{"jsonrpc": "2.0", "method": "Addons.ExecuteAddon","params": {"addonid": "service.autostop"}, "id": 2}`

**Comment by jbinkley60** [comment]
How about trying this ?

{"jsonrpc": "2.0", "method": "Addons.ExecuteAddon","params":{"addonid":"service.autostop"}, "id":2}

I removed some spaces which I have found can cause parsing errors.  I am not a JSON RPC expert.  I presume you have the  addon loaded on your test system ?

**Comment by jbinkley60** [comment]
I believe installing the addon fixed the issue.  The favrourites shouldn't matter.  That is for the Kodi GUI.

Jeff

**Comment by wutschel** [comment]
Thanks for chiming in. It was my bad. I thought the command would be Kodi built-in, but I missed to install your add-on.

**Comment by jbinkley60** [comment]
No problem.  Glad it is working.  To ensure it is operating properly you should se a popup from the addon indicating that the sleep timer value changed, each time you fire the JSON RPC command to call the addon.

**Comment by jbinkley60** [comment]
> Yes, the popup shows each time. So we're good. :)

Great.  Thanks for confirming.  I am not an IOS user but we could look at passing parameters for other things in the future.  I'll close this issue.

**Comment by wutschel** [comment]
> Great. Thanks for confirming. I am not an IOS user but we could look at passing parameters for other things in the future. 

Can you share an example of such script (incl. parameters) which is added to favorites?

**Comment by jbinkley60** [comment]
Well right now Autostop doesn't support passing parameters but I could add the capability.  An example might be if someone wanted to enable the sleep timer or paused playback timer and even set to a specific value (i.e. 60 minutes).  They would get passed to Autostop as sysargv values that I would need to parse.  I'd need to publish what are acceptable commands and I presume you'd program them into your remote software.  If you want to see an example of what it might look like on the receiving side in my addon,  [Here's an example](https://github.com/Conceiva/MezzmoKodiPlugin/blob/Kodi-19%2B/resources/lib/utilities.py) from another addon where I pass a lot of data within the addon via this method.  Begin looking at line 637.

On the sending side you just parameterize the call.  So for example::

<favourite name="Autostop Sleep Timer">RunScript("service.autostop","sleep=60')</favourite>

Which should correspond to something like this in JSON PC:

{"jsonrpc": "2.0", "method": "Addons.ExecuteAddon","params": {"addonid": "service.autostop", "sleep": "60"}, "id": 2}

This is psuedo code and the syntax would need to be confirmed but hopefully this makes sense.

**Comment by wutschel** [comment]
Ok, let's wait until we have an example for this. Maybe it is even possible to set parameters for the command line itself?
