### ISSUE TITLE
tv station logo scaling

### ISSUE THREAD

**Issue by howie-f** [xbmc/Official-Kodi-Remote-iOS#895]
hi @wutschel, this looks weird : v1.13 (3924) on iPad Air 2 (guess the problem is the CD-case again 🤔)

![EFD0A1CE-ED76-4270-AF22-E384EFBCB89D](https://user-images.githubusercontent.com/58829855/236018196-17a73d24-af6a-40a2-b877-ecbfbe04e3fa.png)

on v1.12.1 (3752) iPhone 6 it is fine though.

**Comment by wutschel** [comment]
Thanks, nice learning on how to properly use `clipsToBounds`, `UIViewContentModeScaleAspectFill` and `UIViewContentModeScaleAspectFit`.
