### ISSUE TITLE
[Feature Request] Optimization for iOS 17 devices compatibility 

### ISSUE THREAD

**Issue by RFL0WGitPR** [xbmc/Official-Kodi-Remote-iOS#933]
Dear Kodi Remote Development Team,

I hope this message finds you well. I would like to provide some constructive feedback regarding the Kodi Remote app for iOS devices. As a dedicated user of Kodi and the iOS platform, I believe that optimizing the Kodi Remote to support iOS 17 devices, both 32-bit and 64-bit, for iPhone, iPad, and Apple TV devices, would greatly enhance the user experience and extend the app's compatibility.

Optimizing the Kodi Remote for iOS 17 devices would ensure that users with the latest iOS version can continue to enjoy seamless control and interaction with their Kodi media center. By supporting both 32-bit and 64-bit architectures, you would cater to a wider audience and make sure that users with older devices can still benefit from this valuable app.

Here are a few specific suggestions to consider:

1. **Compatibility Testing**: Thoroughly test the Kodi Remote on various iOS 17 devices, including iPhone, iPad, and Apple TV, to ensure that it functions flawlessly without any compatibility issues.

2. **Performance Optimization**: Optimize the app's performance to take full advantage of the hardware capabilities of iOS 17 devices, delivering a smooth and responsive user experience.

3. **User Interface Enhancements**: Consider updating the user interface to align with the design principles and features introduced in iOS 17, providing a modern and cohesive look and feel.

4. **Bug Fixes and Stability**: Address any existing bugs and stability issues to guarantee a reliable and frustration-free experience for users.

5. **64-bit Transition**: Ensure that the app is fully 64-bit compatible to future-proof it for upcoming iOS versions.

By implementing these improvements, you can ensure that the Kodi Remote remains a top choice for iOS users who rely on Kodi for their media needs. Your dedication to keeping the app up-to-date and optimized for the latest iOS versions is greatly appreciated by the Kodi community.

Thank you for your attention to this feedback, and I look forward to seeing the continued development and enhancement of the Kodi Remote app.

**Comment by kambala-decapitator** [comment]
this "feature request" contains zero usefulness
