### ISSUE TITLE
Feature request: bring the "actions menu" button to the iPhone app

### ISSUE THREAD

**Issue by alexmcan** [xbmc/Official-Kodi-Remote-iOS#94]
The iPad Kodi remote app has a nice "actions menu" that is available while pressing a button that looks like a Shutdown icon. It has things like Power off System, Hibernate, Suspend, Reboot, Quit Kodi application, Update Audio Library etc. It would be valuable to bring that same functionality on the iPhone. I mainly use it to Shutdown/Reboot the Ubuntu music server it runs on and also to Update my audio library once I made changes to it. I apologize if that button is already available on iPhone, but I wan't able to find it.
![IMG_0020](https://user-images.githubusercontent.com/13875806/75594587-32d9a380-5a57-11ea-920a-13b426e2907a.png)

**Comment by joethefox** [comment]
Hello,

yes, this actions are also availables in iPhone. They are under the right menu once you are connected to your kodi instance.

![Simulator Screen Shot - iPhone Xs - 2020-03-01 at 13 30 54](https://user-images.githubusercontent.com/1732455/75625716-148fb700-5bc1-11ea-8510-567b23f42702.png)

![Simulator Screen Shot - iPhone Xs - 2020-03-01 at 13 30 06](https://user-images.githubusercontent.com/1732455/75625686-ce3a5800-5bc0-11ea-8555-b917f0feac7c.png)

**Comment by alexmcan** [comment]
Got it. I missed it since it was on the windows where the Kodi servers are configured (I have a few). Thanks a lot. The remote app is fantastic by the way!
