### ISSUE TITLE
Seeking doesn't work with Kodi Matrix

### ISSUE THREAD

**Issue by popcornmix** [xbmc/Official-Kodi-Remote-iOS#95]
Since https://github.com/xbmc/xbmc/pull/15939 was merged, the up/down/left/right seeking buttons when playing a video no longer work.

Apparently these were using ambiguous/duplicate methods that have been removed.
Any chance of updating?

**Comment by nkichukov** [comment]
I am also affected by this bug.

**Comment by graysky2** [comment]
With RC1 looming, please fix and push.  Thanks!

**Comment by wutschel** [comment]
Can we close this issue? The PR has been merged already.

**Comment by nkichukov** [comment]
When would an updated version make it into the app store?

**Comment by kambala-decapitator** [comment]
@nkichukov when we're done with bug fixes. I expect beginning of February.
