### ISSUE TITLE
Posters are not showing with 19 Alpha

### ISSUE THREAD

**Issue by heitbaum** [xbmc/Official-Kodi-Remote-iOS#96]
Since testing 19 alpha/beta the Posters no longer show up in the iOS App.

**Comment by wutschel** [comment]
Should also fix issue https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/88.

**Comment by wutschel** [comment]
Fix is merged, this can be closed.

**Comment by kambala-decapitator** [comment]
please check in TF build 1968

**Comment by heitbaum** [comment]
@kambala-decapitator / @wutschel - I can configure that movie posters are back in 1968 on the iPad Pro 9.7” 🎉👍
