### ISSUE TITLE
Remote speed buttons hint is incorrect

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#980]
I thought that "increment / decrement speed" do exactly that - change playback speed, but in fact they work as rewind / fast forward.

![image](https://github.com/xbmc/Official-Kodi-Remote-iOS/assets/1557784/8117d894-6675-4e10-b6aa-284974cd373b)

**Comment by wutschel** [comment]
Well, long press calls `Player.SetSpeed` with parameter `"speed": "decrement"` or `"speed": "increment"`. The available speeds are -32, -16, -8, -4, -2, -1, +1, +2, +4, +8, +16, +32. The increment/decrement just switches to up/down these options obviously. I guess the description is a bit misleading, so is the JSON API method's name.

**Comment by kambala-decapitator** [comment]
would be great to improve the description

also, as I found out, the API doesn't have command to change playback speed at all :(

**Comment by wutschel** [comment]
When starting from normal playback speed "Increment speed" is quite correct. When the speed is already increased even "decrease speed" is ok. The description mismatches once you get into backwards playback/seek. Any good suggestion from you side? Besides the best translation, it will be quite some work to update all translations and screens (these are images for each language).

**Comment by kambala-decapitator** [comment]
> When starting from normal playback speed "Increment speed" is quite correct

well, it's still "Fast forward", this title is even visible in UI. In my view "speed" should also change audio speed (the behavior that you get with Alt + left/right arrow), that you can still actually watch a movie and not just a series of images.

> The description mismatches once you get into backwards playback/seek

indeed, you're right. I also don't have "continuous" playback once I set FF speed to 8/16, but I guess that's because my server is limited to 100 Mbit/s in bandwidth.

> Any good suggestion from you side?

I'd just go with the traditional Rewind / Fast Forward. Also the main action should be Seek or Jump, and the UI also says "Seeking".

> it will be quite some work to update all translations and screens (these are images for each language).

oh damn... Do you still have the source images (PSD or w/e)?

**Comment by wutschel** [comment]
Yes, we have them even in our repo (as pptx under "Templates" folder).
