### ISSUE TITLE
App menu sorted alphabetically

### ISSUE THREAD

**Issue by fischcode** [xbmc/Official-Kodi-Remote-iOS#987]
Since a number of releases, the official kodi remote sorts output from many apps alphabetically. While this may make sense in the case of a list of titles, many apps return structured lists that follow there own logic and shouldn't be sorted.
In addition to the [YT Music EXP](https://github.com/Goldenfreddy0703/plugin.audio.ytmusic.exp) addon, this also affects apps from the official kodi repository such as Radio (3.0.9+matrix.1 by Tristan Fischer, enen92) and ORF Radiothek (0.1.3+matrix.1 by sofaking) but not others such as ARD Mediathek (6.0.0 by sarbes) and ORF TVThek (0.12.9+matrix.1 by sofaking): Before I invest a lot of time trying to figure out the pattern behind this: Does anyone already know what causes this difference? Presumably it is connected to the metadata the app sends together with its menu items, and I am more than willing to adjust the way YT Music EXP renders its menu to prevent it from being sorted alphabetically.

**Comment by wutschel** [comment]
Possibly this is caused by requesting content in sorted order. I will try to look into this for the plugins you mentioned.

**Comment by wutschel** [comment]
Found the issue. There are different ways to enter plugins, e.g. via Music, Movies, Videos and TV Shows menu. I always tested YouTube via entering the plugins from the Videos menu. This worked. When entering from the other menus the App was asking Kodi to deliver the results sorted by "label". I now changed this to sort by "none", which makes it work as intended.
