### ISSUE TITLE
Switch to xcode 15

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#991]
ITMS-90725: SDK version issue - This app was built with the iOS 16.2 SDK. Starting April 29, 2024, all iOS and iPadOS apps must be built with the iOS 17 SDK or later, included in Xcode 15 or later, in order to be uploaded to App Store Connect or submitted for distribution.

**Comment by wutschel** [comment]
Just installed Xcode 15.2 and ran a first build on iPhone and iPad iOS 17.2 simulators. No trouble so far. This for sure needs more testing, but already is comforting.

**Comment by wutschel** [comment]
Only change for now is to set the deployment target to iOS 12. Otherwise a warning is thrown, I guess upload to AppStore would also be blocked?

**Comment by kambala-decapitator** [comment]
I suggest to release what we have with Xcode 14 and start preparing next release with 15.

> Only change for now is to set the deployment target to iOS 12. Otherwise a warning is thrown, I guess upload to AppStore would also be blocked?

yes, I guess so, but haven't tried. Raising to 12 is safe anyway as all devices that run 11 can be updated to 12.

**Comment by kambala-decapitator** [comment]
exactly

**Comment by wutschel** [comment]
We can close this with your latest changes.

**Comment by kambala-decapitator** [comment]
#999
