### ISSUE TITLE
New NowPlaying Layout

### ISSUE THREAD

**Issue by StyleHack** [xbmc/Official-Kodi-Remote-iOS#994]
The new Layout is ugly. Please undo this

**Comment by wutschel** [comment]
That's why this is only a test build, not merged and shared via TF to collect som feedback. I like it a lot, but this is personal taste.

What specifically you do not like?

**Comment by wutschel** [comment]
Please also see discussion going on here: https://forum.kodi.tv/showthread.php?tid=359717&pid=3185552#pid3185552

**Comment by wutschel** [comment]
Next TF build 1.15 (4259.42) with updated layout has been shared: https://forum.kodi.tv/showthread.php?tid=359717&pid=3187038#pid3187038

**Comment by wutschel** [comment]
Next TF build out 1.15 (4264.43): https://forum.kodi.tv/showthread.php?tid=359717&pid=3187835#pid3187835
