### ISSUE TITLE
Ipad battery drain

### ISSUE THREAD

**Issue by sirop2** [xbmc/Official-Kodi-Remote-iOS#995]
Hi, i don't know why but kodi drain all my ipad battery, in one hour 90% of the battery is drained by the app

I use it with a movie streaming extension named Vstream!

![image](https://github.com/xbmc/Official-Kodi-Remote-iOS/assets/20713597/7f8b1ef5-5dc4-41f5-a039-74ec20b519d6)
- Ipad Pro 12.9 M.2 (2022) ios 17.1.2

- Kodi 20.3

**Comment by chewitt** [comment]
https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons

Karma :)

**Comment by wutschel** [comment]
Just to mention: the report refers to Kodi, not to the Kodi Remote App.

**Comment by sirop2** [comment]
Oh 🤦‍♂️
